emqx/emqx-dashboard5

public/static/schema.json, src/components/SchemaForm.vue, src/hooks/Config/useSchemaForm.ts, src/i18n/BasicConfig.js, src/i18n/components.js, src/router/index.ts, src/store/index.ts, src/views/Base/LeftBar.vue, src/views/Config/BasicConfig/BasicConfig.vue, src/views/Config/BasicConfig/components/Cluster.vue
@Kinplemelon Note:
1. scheam.json is the default config schema form render file, the emqx build will replace it with the new file.
2. Currently in this PR it's just a matter of building the schema.json content into a data format that works well on the front end and printing it to the page
=> feat(config): add basic config page

src/common/auth.ts, src/components/SchemaForm.tsx, src/i18n/BasicConfig.js, src/style/common.scss, src/views/Clients/ClientDetails.vue, src/views/Clients/Clients.vue, src/views/Config/Monitoring/AlarmSettings.vue, src/views/Subscriptions/Subscriptions.vue, src/views/Topics/Topics.vue
The client id is still not visible to clients with spaces, but at least it is now possible to click into the details pageÎ
https://user-images.githubusercontent.com/26165221/195291096-474a1382-ef4d-4ca7-bd8a-8f21d5001234.mov
=> feat(clients & subs): some key fields are displayed with spaces reserved

src/hooks/Rule/bridge/useResourceOpt.ts, src/types/rule.d.ts
Modify the return value of the method, which has no effect on the two data bridges of the open source version
=> refactor(bridge): remove `enable_batch`

src/hooks/Config/useSchemaForm.ts
don't have influence, just saw that there is no need to let `schema` be reactive
=> refactor(schema form): do not let `schema` be reactive

src/views/RuleEngine/Bridge/BridgeDetail.vue
before
https://user-images.githubusercontent.com/26165221/219530057-28d26a89-1c2f-4064-afc7-a9e406eef313.mov
after 
https://user-images.githubusercontent.com/26165221/219530073-f386ec05-bb5e-44de-a025-c9655f473611.mov
If you think it's really getting better, you can merge this PR, otherwise you can close it
=> refactor(bridge detail): optimized user experience

src/i18n/RuleEngine.js
This is a temporary solution, I have to find a way to get the content of the object in oneof
=> fix(bridge kafka): add missing text

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts, src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeHttpConfig.vue
`resource_opts` already have such option, and keeping both could lead to inconsistent behavior.
Related PR: https://github.com/emqx/emqx/pull/10051
=> chore: remove root `request_timeout` from GCP PubSub bridge (e5.0)

vue.config.js
Split the monaco-editor library into separate code blocks
For resolve this... I don't understand why it has become like this. There have been no changes to the relevant code of Monaco since v1.2.1.
And I found that there was no such problem before this commit https://github.com/emqx/emqx-dashboard5/commit/37326c9d6b3480e8b62c9987985221c060f90020, and it triggered the problem in some magical way.
=> chore(vue.config.js): optimized package size

src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeHttpConfig.vue
Fixes https://emqx.atlassian.net/browse/EMQX-10001
Related backend PR: https://github.com/emqx/emqx/pull/10821
=> fix(webhook): use `resource_opts.request_timeout` field for bridge (e5.0)

src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeInfluxdbConfig.vue, src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue, src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgePulsarConfig.vue, src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbWriteSyntaxInput.vue
=> refactor(bridge): hide resource_opt configs by default

src/common/CustomMessage.ts, src/style/normalize.scss
https://emqx.atlassian.net/browse/ED-566
Fixed from two aspects:
1. Call the close method 2 seconds after duration
2. Move the close button to the top right corner of the pop-up
=> fix(message): error msg cannot be closed when error msg is too long

src/hooks/Rule/connector/useMixedConnectorList.ts, src/i18n/RuleEngine.js, src/views/RuleEngine/Connector/Connector.vue, src/views/RuleEngine/components/TableItemDropDown.vue
Handle the situation where connectors created with v2 api cannot be viewed on the dashboard
=> refactor(connector): handling connectors which can not view

src/views/Clients/ClientDetails.vue
It feels like there is still some distance before it becomes available, so I hide it for now.
=> refactor(client): temporarily hide button to view the message queue list

src/i18n/RuleEngine.js, src/views/RuleEngine/Schema/components/SchemaRegistryForm.vue
=> refactor(schema): remove validation for `$schema`

src/i18n/BasicConfig.js, src/i18n/Rule.js, src/views/Config/BasicConfig/Mqtt.vue
https://emqx.atlassian.net/browse/ED-1366
=> fix(mqtt): add rules for check `client_attrs_init`

src/i18n/Base.js, src/i18n/Extension.js, src/views/AdvancedMQTT/DelayedPub.vue, src/views/AdvancedMQTT/Rewrite.vue, src/views/Clients/components/ClientFieldSelect.vue, src/views/Config/BasicConfig/SystemTopics.vue
https://emqx.atlassian.net/browse/ED-1396
https://emqx.atlassian.net/browse/ED-1407
https://emqx.atlassian.net/browse/ED-1409
=> refactor(topic rewrite): add tip and remove rule for `re`

src/types/schemas/banned.schemas.ts, src/types/schemas/rules.schemas.ts, src/views/Dashboard/components/PolylineChart.vue
https://emqx.atlassian.net/browse/ED-1607
=> fix(overview): unit in tooltip

src/api/cluster.ts, src/api/ruleengine.ts, src/common/tools.ts, src/hooks/Rule/schema/useExternalSchemaType.ts, src/i18n/components.js, src/router/index.ts, src/types/schemas/actions.schemas.ts, src/types/schemas/authentication.schemas.ts, src/types/schemas/bridges.schemas.ts, src/types/schemas/cluster.schemas.ts, src/types/schemas/connectors.schemas.ts, src/types/schemas/gatewayAuthentication.schemas.ts, src/types/schemas/gatewayListeners.schemas.ts, src/types/schemas/schemaRegistry.schemas.ts, src/types/typeAlias.ts, src/views/Config/ClusterLinking/components/ClusterLinkingOverview.vue, src/views/General/resource_dict.json, src/views/RuleEngine/Schema/ExternalSchema.vue, src/views/RuleEngine/Schema/ExternalSchemaCreate.vue, src/views/RuleEngine/Schema/ExternalSchemaDetail.vue, src/views/RuleEngine/Schema/Schema.vue, src/views/RuleEngine/Schema/SchemaCreate.vue, src/views/RuleEngine/Schema/SchemaDetail.vue, src/views/RuleEngine/Schema/components/ExternalSchemaConfluentForm.vue, src/views/RuleEngine/Schema/components/ExternalSchemaForm.vue
https://emqx.atlassian.net/browse/ED-1587
https://emqx.atlassian.net/browse/ED-1614
=> feat(external schema): init external schema

src/hooks/Rule/rule/useRuleForm.ts, src/types/rule.d.ts, src/views/RuleEngine/components/RuleForm.vue
Every time a new rule is created, it is enabled by default, but there is no 'enable' field. So, let's add a default value. :)
> This change has no impact on users; other fields (description, sql) have default values when creating a new rule, but this one does not, which feels a bit Inconvenient and inconsistent.
=> chore: add a default(true) value for enable when creating rule

src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts, src/hooks/Rule/useDataHandler.ts
In version 581, the IoTDB thrift driver needs to hide the ssl configuration, the dashboard also removes the ssl configuration when submitting for insurance. After confirming, we can also submit the default ssl configuration, just make sure `ssl.enable` is `false`
=> refactor(connector): hide `ssl` for IoTDB thrift

src/api/common.ts, src/common/http.js, src/common/tools.ts
I'm not sure this is the right way to handle it. Please take a look.
https://emqx.atlassian.net/browse/ED-1654
---
This pull request introduces several changes to improve the handling of whitespace in HTTP requests and to add a utility function for trimming values. The most important changes include modifying the login function to keep spaces, updating the HTTP request interceptor to trim values unless specified otherwise, and adding a new utility function to handle trimming.
* [`src/api/common.ts`](diffhunk://#diff-62eba76fe6cadaa56e99795f9b9fd052fa75b11f8d2a22bdcb0519eb43f723dcL20-R20): Modified the `login` function to include a `keepSpaces` option in the HTTP request.
* [`src/common/http.js`](diffhunk://#diff-8b3981483821f08209fd626431b1a580791498b11a161117bdd70bc8e7607a14R12): Added …
=> refactor(global): remove spaces before and after form values

src/common/tools.ts, src/components/FormItemLabel.vue, src/components/MarkdownContent.vue, src/components/Metrics/OverviewMetrics.vue, src/components/Metrics/TypeMetricsItem.vue, src/components/ObjectArrayEditor.vue, src/components/SchemaForm.tsx, src/hooks/useMetrics.ts, src/i18n/RuleEngine.js, src/schemaText/schema-text-en.json, src/schemaText/schema-text-zh.json, src/views/Config/BasicConfig/Retainer.vue, src/views/RuleEngine/Bridge/Components/BridgeItemOverview.vue
https://emqx.atlassian.net/browse/ED-1596
https://emqx.atlassian.net/browse/ED-1657
=> refactor(action): adapt queue bytes

src/hooks/Auth/useDatabaseConfigForm.ts, src/i18n/Gateway.js, src/views/Auth/AuthnCreate.vue, src/views/Auth/components/DatabaseConfig.vue, src/views/Auth/components/JwtConfig.vue, src/views/Auth/components/LdapConfig.vue, src/views/Base/Layout.vue, src/views/Gateway/Gateway.vue
https://emqx.atlassian.net/browse/ED-1728
https://emqx.atlassian.net/browse/ED-1739
https://emqx.atlassian.net/browse/ED-1732
=> fix(auth): use CustomInputPassword component

src/common/tools.ts, src/i18n/Auth.js, src/i18n/Base.js, src/i18n/Extension.js, src/types/extension.d.ts, src/types/schemas/actions.schemas.ts, src/types/schemas/sources.schemas.ts, src/views/Auth/components/DatabaseConfig.vue, src/views/Config/BasicConfig/Retainer.vue, src/views/RuleEngine/components/ActionAndSourceList.vue
https://emqx.atlassian.net/browse/ED-1743
https://emqx.atlassian.net/browse/ED-1749
=> refactor(retainer): adapt `max_publish_rate`

src/i18n/components.js
https://emqx.atlassian.net/browse/ED-1748
This pull request includes various translation updates in the `src/i18n/components.js` file. The changes primarily focus on improving the accuracy and consistency of the English translations.
Translation updates:
* Updated `diagnose` to use "Diagnostics Tools" instead of "Diagnose"
* Changed `extension` to "Extensions" from "Extension"
* Modified `audit-log` to "Audit Logs" from "Audit Log"
* Updated `schema` to "Schema Registry" from "Schema"
* Changed `mqtt-session` to "Sessions" from "Session"
=> refactor(i18n): update component translations to plural and more descriptive forms
