emqx/emqx-dashboard5

src/hooks/Auth/useAuthnCreate.js
src/hooks/Auth/useAuthzCreate.js
src/hooks/Auth/useDatabaseConfig.js
src/views/Auth/components/DatabaseConfig.vue

New bugs were created in the process of fixing bugs

Some Field Adjustments

---

src/views/Advanced/components/subscribe.vue

just want to confirm why there are two form components here, and whether there will be any bad things if they are deleted😂

fix(advanced sub): sub form

---

src/components/MarkdownContent.vue
src/i18n/Base.js
src/views/Config/ConfigDocs.vue

Hi! @zmstone I added a TOC of the Config Document and fixed the issue of not being able to scroll the page based on anchor points in this PR. You can test the build package by downloading it from the link below 👇
https://github.com/emqx/emqx-dashboard-web-new/actions/runs/1810817315

feat(config): add toc and fix anchor jumping

---

public/static/config.md
src/i18n/Clients.js
src/style/common.scss
src/views/Advanced/components/message.vue
src/views/Clients/ClientDetails.vue
src/views/Clients/Clients.vue
src/views/RuleEngine/Bridge/DataBridge.vue
src/views/RuleEngine/components/IoTForm.vue
src/views/RuleEngine/components/RuleTopology.vue

- config: delete $event/ prefix when config event message
- client: added some stats for the updated two fields
- a style error
- a placeholder error
- reorganize the code for the RuleTopology component

Some Changes

---

src/i18n/Gateway.js
src/views/Gateway/GatewayCreate.vue
src/views/Gateway/components/listeners.vue
src/views/Gateway/components/stompBasic.vue

Gateway Create

---

src/i18n/Clients.js
src/views/Auth/AuthnDetails.vue
src/views/Auth/style/auth.scss
src/views/Clients/ClientDetails.vue
src/views/Gateway/components/clients.vue

Gateway Optimization

---

src/components/InfoTooltip.vue
src/hooks/Rule/topology/useTopologyNodeTooltipNEvent.ts
src/i18n/RuleEngine.js
src/style/rule.scss
src/views/RuleEngine/Bridge/Components/BridgeItemOverview.vue
src/views/RuleEngine/IoT/IoT.vue
src/views/RuleEngine/IoT/IoTDetail.vue
src/views/RuleEngine/IoT/components/RuleItemOverview.vue
src/views/RuleEngine/IoT/components/TableItemDropDown.vue

- List Page
- Adjusted table columns
- Add copy and reset statistics operation
- Detail Page
- Add Overview

IoT List And Detail Page

---

src/components/Monaco.vue
src/i18n/RuleEngine.js
src/style/rule.scss
src/views/Diagnose/LogTrace/LogTraceDetail.vue
src/views/RuleEngine/components/IoTForm.vue
src/views/RuleEngine/components/RuleOutputs.vue

- extract the rule outputs component
- updated the props of monaco & fixed a bug

Monaco Component Support Model Value Binding

---

src/components/SubTabMenu.vue
src/hooks/useSubTabMenu.ts
src/types/config.d.ts
src/views/Config/Advanced/Advanced.vue
src/views/Config/Advanced/components/message.vue
src/views/Config/Advanced/components/rewrite.vue
src/views/Config/Advanced/components/subscribe.vue

@Kinplemelon I added this component because I found that there are other pages that will be used, and I've only refactored the advanced page so far.

refactor(components): add sub tab menu component

---

src/i18n/RuleEngine.js
src/views/RuleEngine/components/FromSelect.vue
src/views/RuleEngine/components/FromSelectList.vue
src/views/RuleEngine/components/IoTForm.vue

https://user-images.githubusercontent.com/26165221/156290495-b73f03a2-7177-43f5-91a5-92f774f756d5.mov
this component

feat(rule): from select

---

.eslintrc.js
src/components/SchemaForm.tsx
src/style/schemaForm.scss
src/views/General/Backup.vue
vue.config.js

WIP
Now we can see some config form:

style(schema): add schema form scss

---

src/components/InputWithUnit.vue
src/components/SchemaForm.tsx
src/types/schemaForm.d.ts

@Kinplemelon Input with unit component support pass string array or object array.
It's easier to use, see the code, but I'm not sure if there will be problems, maybe I'll merge first but please help review!!

refactor(inputWithUnit): support string arrary type

---

src/api/config.ts
src/components/SchemaForm.tsx
src/hooks/Config/useSchemaForm.ts
src/style/schemaForm.scss
src/types/config.d.ts
src/types/schemaForm.d.ts
src/views/Config/BasicConfig/components/Cluster.vue

WIP:
Support update the cluster configs. But now can not bind the nested object value.

feat(cluster): completed the cluster config page

---

src/api/config.ts
src/components/ArrayEditor.vue
src/components/SchemaForm.tsx
src/i18n/BasicConfig.js
src/types/config.d.ts
src/views/Config/BasicConfig/BasicConfig.vue
src/views/Config/BasicConfig/components/Dashboard.vue

feat(config): add dashboard config page

---

src/components/InputWithUnit.vue
src/components/Oneof.vue
src/components/SchemaForm.tsx
src/components/TimeInputWithUnitSelect.vue
src/style/schemaForm.scss
src/types/config.d.ts

This component allows multiple types of values to be selected, with only one and only one taking effect. @Kinplemelon

feat(components): add oneof component

---

.eslintrc.js
src/api/auth.ts
src/api/exhook.ts
src/hooks/Auth/useHandleAuthnItem.ts
src/hooks/Auth/useHandleAuthzItem.ts
src/hooks/Exhook/useHandleExhookItem.ts
src/hooks/Plugins/usePluginItem.ts
src/hooks/useMove.ts
src/types/enum.ts
src/views/Auth/Authn.vue
src/views/Auth/Authz.vue
src/views/Auth/components/TableDropdown.vue
src/views/Exhook/Exhook.vue
src/views/Plugins/Plugins.vue
src/views/RuleEngine/Bridge/BridgeCreate.vue
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/BridgeHttpConfig.vue
src/views/RuleEngine/Bridge/BridgeMqttConfig.vue
src/views/RuleEngine/Bridge/DataBridge.vue
src/views/RuleEngine/Connector/Connector.vue
src/views/RuleEngine/Connector/ConnectorCreate.vue
src/views/RuleEngine/IoT/IoT.vue
src/views/RuleEngine/IoT/IoTCreate.vue
src/views/RuleEngine/IoT/IoTDetail.vue
src/views/RuleEngine/components/ConnectorDialog.vue
src/views/RuleEngine/components/IoTForm.vue
src/views/RuleEngine/components/RuleOutputsDialog.vue
src/views/RuleEngine/components/SQLTestDialog.vue
src/views/RuleEngine/components/TestSQLContextForm.vue

- unified processing logic
- fixed bug in auth

Handle Event That Reorder Objects

---

src/api/diagnose.ts
src/hooks/Auth/useHandleAuthnItem.ts
src/hooks/Auth/useHandleAuthzItem.ts
src/hooks/useMove.ts
src/types/systemModule.d.ts
src/views/Auth/Authn.vue
src/views/Auth/Authz.vue
src/views/Diagnose/components/SlowSubData.vue
src/views/Exhook/Exhook.vue
src/views/Exhook/ExhookCreate.vue
src/views/Plugins/Plugins.vue

- handle the case where an obj is moved to the last in the filtered state of the obj list
- fixed the bug when show table data in slow sub

Set Default Value for Some Fields When Creating Exhook

---

src/components/TimeInputWithUnitSelect.vue
src/style/schemaForm.scss
src/views/Config/BasicConfig/BasicConfig.vue
src/views/Config/BasicConfig/components/Cluster.vue
src/views/Config/BasicConfig/components/Dashboard.vue
src/views/Config/BasicConfig/components/Log.vue
src/views/Config/BasicConfig/components/Zone.vue

…the filtered state of the plugin list

style(config): refactor config pages styles

---

src/hooks/Rule/bridge/useBridgeDataHandler.ts
src/i18n/RuleEngine.js
src/views/RuleEngine/Bridge/BridgeCreate.vue
src/views/RuleEngine/Bridge/BridgeMqttConfig.vue

Some Fields Adjustment in Bridge

---

src/common/tools.ts
src/components/SchemaForm.tsx
src/style/schemaForm.scss

feat(config): add reset config value method

---

src/components/SchemaForm.tsx
src/i18n/Auth.js
src/i18n/BasicConfig.js
src/style/schemaForm.scss
src/views/Auth/AuthnCreate.vue
src/views/Auth/AuthzCreate.vue
src/views/Auth/components/BuiltInConfig.vue

feat(config): add tooltip for read-only config item

---

public/index.html
src/hooks/Auth/useAuth.ts
src/i18n/Auth.js
src/i18n/Dashboard.js
src/style/schemaForm.scss
src/views/Auth/Authn.vue
src/views/Auth/AuthnDetails.vue
src/views/Auth/Authz.vue
src/views/Auth/AuthzDetails.vue
src/views/Dashboard/Overview.vue
src/views/Dashboard/components/NodesGraph.vue
src/views/Dashboard/components/PolylineCards.vue
src/views/Dashboard/components/PolylineChart.vue
src/views/Dashboard/components/SimpleLine.vue

@zmstone Hi, stone. This PR contains some changes to the English content and I would like to ask you to review it, thank you very much.

fix(overview): optimized contents

---

src/i18n/Auth.js
src/i18n/components.js
src/style/normalize.scss
src/views/Auth/AuthnDetails.vue
src/views/Auth/AuthzDetails.vue
src/views/Auth/AuthzSetting.vue
src/views/Auth/components/BuiltInManager.vue
src/views/Auth/components/DataManager.vue
src/views/Auth/components/HttpConfig.vue
src/views/Auth/components/TLSConfig.vue
src/views/Auth/components/TableDropdown.vue
src/views/Auth/style/auth.scss
src/views/Dashboard/Overview.vue
src/views/RuleEngine/components/TLSConfig.vue

@zmstone It's now called a Websocket Client
@Kinplemelon In the project, as long as the code is not used, currently need to delete, it without comments, because it will bring a lot of interference, there are similar functions we need to re-write the code to reach the latest.

fix(overview): remove useless codes

---

src/components/InfoTooltip.vue
src/i18n/Auth.js
src/views/Auth/components/BuiltInManager.vue

@Kinplemelon tooltip component doesn't seem to have the width props.

feat(auth): add topic tips

---

src/views/Config/Advanced/Advanced.vue

cause by: https://emqx.atlassian.net/wiki/spaces/EMQX/pages/359661649/Lifecycle+Events

fix(advanced): hide event message page

---

src/main.ts
src/style/normalize.scss
src/style/themes/dark.scss
src/style/themes/light.scss
src/views/Base/NavHeader.vue

styles(element): refactor message component style

---

src/style/normalize.scss
src/style/themes/dark.scss
src/style/themes/light.scss
src/views/Base/Layout.vue
src/views/Base/LeftBar.vue
src/views/Dashboard/Overview.vue

refactor(scss): add theme files

---

src/style/normalize.scss
src/style/themes/dark.scss
src/style/themes/light.scss
src/views/Base/Layout.vue
src/views/Base/LeftBar.vue
src/views/Dashboard/Overview.vue

Reverts emqx/emqx-dashboard-web-new#184

Revert "refactor(scss): add theme files"

---

src/style/themes/dark.scss
src/style/themes/light.scss
src/views/Base/Layout.vue
src/views/Base/LeftBar.vue
src/views/Base/NavHeader.vue

refactor(navheader): refactor navbar header styles

---

src/hooks/Overview/useDrawNodesGraph.ts
src/types/dashboard.d.ts
src/types/enum.ts

feat(overview): add running status to node and add active style in node graph

---

src/style/normalize.scss
src/style/themes/dark.scss
src/style/themes/light.scss
src/views/Base/Layout.vue
src/views/Base/LeftBar.vue
src/views/Base/NavHeader.vue

refactor(menu): refactor horizontal menu

---

src/i18n/Dashboard.js
src/style/normalize.scss
src/style/themes/dark.scss
src/style/themes/light.scss
src/views/Clients/Clients.vue
src/views/Dashboard/Nodes.vue
src/views/Dashboard/Overview.vue
src/views/Dashboard/components/NodesGraphCard.vue
src/views/Dashboard/components/PolylineChart.vue
src/views/Dashboard/components/SimpleLine.vue
src/views/Gateway/components/clients.vue

fix(chart): modify charts styles and fix can not show tooltip

---

src/style/management.scss
src/style/normalize.scss
src/views/Clients/Clients.vue
src/views/RuleEngine/components/IoTForm.vue
src/views/Subscriptions/Subscriptions.vue

style(rule & websocket): style of btn

---

src/components/Breadcrumb.vue
src/style/common.scss
src/views/Dashboard/NodeDetail.vue

feat(breadcrumb): add breadcrumb component

---

src/i18n/Dashboard.js
src/style/common.scss
src/views/Dashboard/Metrics.vue
src/views/Dashboard/components/IntegrationMetrics.vue

refactor(metrics): refactor metrics page

---

src/hooks/Auth/useAuthn.ts
src/hooks/Auth/useAuthz.ts
src/hooks/useI18nTl.ts
src/i18n/Auth.js
src/i18n/Base.js
src/style/common.scss
src/style/rule.scss
src/views/Auth/AuthnDetails.vue
src/views/Auth/AuthzDetails.vue
src/views/Auth/components/AuthItemOverview.vue
src/views/Auth/style/auth.scss
src/views/RuleEngine/IoT/components/RuleItemOverview.vue

feat(auth): add overview to auth in detail page

---

src/components/commonPagination.vue
src/style/normalize.scss
src/views/Dashboard/components/PolylineCards.vue

style(pagination): refactor pagination styles

---

src/api/config.ts
src/components/ArrayEditor.vue
src/components/SchemaForm.tsx
src/components/SubTabMenu.vue
src/i18n/BasicConfig.js
src/style/common.scss
src/style/normalize.scss
src/style/schemaForm.scss
src/types/config.d.ts
src/views/Config/Advanced/Advanced.vue
src/views/Config/Advanced/components/postpone.vue
src/views/Config/Advanced/components/retainer.vue
src/views/Config/Advanced/components/rewrite.vue
src/views/Config/Advanced/components/subscribe.vue
src/views/Config/Advanced/components/sysTopics.vue
src/views/Config/BasicConfig/BasicConfig.vue
src/views/Config/BasicConfig/components/Telemetry.vue
src/views/Config/BasicConfig/components/Zone.vue
src/views/RuleEngine/FlowChart/FlowChart.vue

refactor(config): refactor config page

---

public/static/hot-config-schema-en.json
public/static/hot-config-schema-zh.json
src/api/config.ts
src/components/SchemaForm.tsx
src/hooks/Config/useSchemaForm.ts
src/i18n/BasicConfig.js
src/types/config.d.ts
src/views/Config/BasicConfig/BasicConfig.vue
src/views/Config/BasicConfig/components/Rate.vue
src/views/Config/BasicConfig/components/Telemetry.vue

feat(config): add rate limite config page

---

src/components/GuideBar.vue
src/components/SubTabMenu.vue
src/components/TLSConfig/TLSBaseConfig.vue
src/components/TLSConfig/TLSEnableConfig.vue
src/style/common.scss
src/style/normalize.scss
src/style/schemaForm.scss
src/style/themes/dark.scss
src/style/themes/light.scss
src/views/Auth/style/auth.scss
src/views/Base/Layout.vue
src/views/Base/LeftBar.vue
src/views/Base/NavHeader.vue
src/views/Config/Advanced/Advanced.vue
src/views/Config/BasicConfig/BasicConfig.vue
src/views/Dashboard/Nodes.vue
src/views/Dashboard/components/NodesGraphCard.vue
src/views/Diagnose/SlowSubConfig.vue
src/views/Plugins/Plugins.vue
src/views/Plugins/components/PluginInfo.vue
src/views/Plugins/components/PluginInfoItem.vue
src/views/RuleEngine/Bridge/BridgeCreate.vue
src/views/RuleEngine/Bridge/DataBridge.vue
src/views/RuleEngine/Connector/ConnectorCreate.vue
src/views/RuleEngine/FlowChart/FlowChart.vue
src/views/RuleEngine/components/RuleOutputs.vue

feat(base): adapted to dark mode

---

src/App.vue
src/assets/theme/editor-dark.json
src/components/Monaco.vue
src/i18n/Dashboard.js
src/i18n/Settings.js
src/router/index.ts
src/store/index.ts
src/style/common.scss
src/views/Auth/components/DatabaseConfig.vue
src/views/Auth/style/authConfig.scss
src/views/Base/LeftBar.vue
src/views/Base/NavHeader.vue
src/views/Dashboard/Nodes.vue
src/views/Dashboard/Overview.vue
src/views/Dashboard/components/PolylineCards.vue
src/views/Diagnose/LogTrace/LogTraceDetail.vue
src/views/RuleEngine/components/IoTForm.vue
src/views/Settings/Settings.vue

feat(settings): add settings page

---

src/components/SchemaForm.tsx
src/i18n/Base.js
src/style/normalize.scss
src/views/Clients/ClientDetails.vue
src/views/Clients/Clients.vue
src/views/Dashboard/Metrics.vue
src/views/Dashboard/NodeDetail.vue
src/views/Dashboard/Nodes.vue
src/views/Dashboard/Overview.vue

fix(nodes): remove memory total value

---

src/views/Clients/Clients.vue
src/views/Gateway/GatewayDetail.vue

fix(gateway): add detail page header

---

src/components/ArrayEditor.vue
src/components/SchemaForm.tsx
src/i18n/BasicConfig.js
src/style/normalize.scss
src/style/schemaForm.scss
src/views/Clients/ClientDetails.vue
src/views/Dashboard/components/NodesGraphCard.vue

refactor(config): add groups radio buttons & refactor array edtior

---

src/api/config.ts
src/components/Oneof.vue
src/components/SchemaForm.tsx
src/i18n/BasicConfig.js
src/views/Config/BasicConfig/components/Zone.vue

refactor(config): rename the global zone to default zone

---

src/views/Dashboard/Overview.vue
src/views/Dashboard/components/RateChart.vue
src/views/Gateway/GatewayCreate.vue

fix(overview): change msg rate display

---

src/api/config.ts
src/style/schemaForm.scss
src/types/config.d.ts
src/views/Config/BasicConfig/BasicConfig.vue
src/views/Config/BasicConfig/components/Rate.vue
src/views/Config/BasicConfig/components/Zone.vue

refactor(config): refactor rate limit page

---

src/i18n/BasicConfig.js
src/views/Config/BasicConfig/components/Rate.vue
src/views/Config/BasicConfig/components/Zone.vue

feat(rate): support add and remove bucket on rate limiter

---

src/api/config.ts
src/components/LimiterSelect.vue
src/components/ListenerDialog/ListenerDialog.vue
src/hooks/Config/useListenerDialog.ts
src/hooks/Config/useListenerUtils.ts
src/i18n/BasicConfig.js
src/style/normalize.scss
src/types/config.d.ts
src/views/Diagnose/SlowSubConfig.vue
src/views/Gateway/components/listeners.vue
src/views/Listener/Listener.vue

feat(listener): support select limiter on listener

---

src/views/RuleEngine/Bridge/BridgeCreate.vue
src/views/RuleEngine/components/AddBridgeOnRule.vue
src/views/RuleEngine/components/RuleOutputs.vue

i fixed a bug but i can't be sure there didn't introduce a new bug, so please help me check 🙏🙏🙏

fix(rule): fixed a bug that can not add multi bridges on rule page

---

src/components/GuideBar.vue
src/hooks/useGuide.ts
src/views/Auth/AuthnCreate.vue
src/views/Auth/AuthzCreate.vue
src/views/Auth/AuthzDetails.vue
src/views/RuleEngine/Bridge/BridgeCreate.vue

feat(auth): show the result of the prev step on step bar

---

src/i18n/Clients.js
src/style/common.scss
src/views/Clients/Clients.vue
src/views/Subscriptions/Subscriptions.vue

refactor(connection&subs): remove filter & style of subs search bar

---

src/views/Base/LeftBar.vue
src/views/RuleEngine/Bridge/BridgeCreate.vue

feat(bridge): show the result of the prev step on step bar

---

src/components/CodeView.vue
src/hooks/Rule/topology/useTopologyNodeTooltipNEvent.ts
src/views/RuleEngine/FlowChart/FlowChart.vue
src/views/RuleEngine/IoT/IoT.vue
src/views/Subscriptions/Subscriptions.vue

style(subs & rule): style of SQL and tooltip of input

---

src/style/common.scss
src/views/Auth/AuthnDetails.vue
src/views/Auth/AuthzDetails.vue
src/views/Auth/components/AuthItemOverview.vue
src/views/Topics/Topics.vue

refactor(auth): optimization overview

---

src/hooks/Rule/topology/useTopologyBridgeData.ts
src/hooks/Rule/topology/useUtilsForTopology.ts

although the bug is not fixed completely, I think it is better than before, so I push a PR first
.

fix(flow): diff topic

---

src/hooks/Rule/topology/topologyType.ts
src/hooks/Rule/topology/useTopology.ts
src/hooks/Rule/topology/useTopologyRuleData.ts
src/hooks/Rule/topology/useUtilsForTopology.ts

fix(flow): node order problem of mqtt source bridge and topic

---

src/views/RuleEngine/Bridge/BridgeCreate.vue

fix(bridge create): error of active step

---

src/hooks/Config/useListenerDialog.ts
src/i18n/Base.js
src/views/Config/Advanced/components/rewrite.vue
src/views/Config/Advanced/components/subscribe.vue
src/views/General/Users.vue

Reverts emqx/emqx-dashboard-web-new#478

Revert "fix(i18n): edited -> updated"

---

src/views/RuleEngine/components/SQLTest.vue

fix(rule): data source validation supports multiple events

---

src/hooks/Rule/bridge/useSyncConfiguration.ts
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeInfluxdbConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeMqttConfig.vue

Fixed a bug where an alert popped up when a bridge action was added to the rule new/edit page without modifying the bridge.

fix(bridge): prevent unintended popup reminder

---

src/i18n/MonitoringIntegration.js
src/views/Config/Monitoring/MonitoringIntegration.vue

refactor(monitoring): refactor monitoring integration page

---

src/api/diagnose.ts
src/i18n/components.js
src/views/Base/Login.vue
src/views/Diagnose/LogTrace/LogTraceDetail.vue

style(login): change some style for beautify style when auto filled

---

src/style/common.scss
src/views/Gateway/Gateway.vue
src/views/Gateway/GatewayDetail.vue

style(gateway): invert icon color when theme is dark

---

package.json
src/components/CodeView.vue
src/i18n/Dashboard.js
src/views/Dashboard/Metrics.vue
yarn.lock

refactor(metrics): desc of metric item

---

src/components/CodeView.vue
src/i18n/MonitoringIntegration.js
src/style/common.scss
src/views/Config/Monitoring/MonitoringIntegration.vue
src/views/Config/Monitoring/assets/emqx5_grafana_template.json
src/views/Config/Monitoring/assets/usePromConfig.ts
src/views/Config/Monitoring/components/HelpDrawer.vue

feat(monitoring): add help step to integration prometheus

---

src/components/CodeView.vue
src/views/Config/Monitoring/components/HelpDrawer.vue

fix(codeView): modify hightlight code theme

---

package.json
src/views/Dashboard/NodeDetail.vue

https://github.com/emqx/emqx/issues/9349

fix(nodes): fix incorrect topics number

---

src/components/GuideBar.vue
src/views/Config/Monitoring/components/HelpDrawer.vue

refactor(monitoring): refactor monitoring integration help page

---

src/hooks/Rule/bridge/useInfluxdbLineProtocol.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbLineProtocolForm.vue

https://user-images.githubusercontent.com/26165221/202675522-0fee3b4b-3052-4f8d-be78-c240192460f6.mov

feat(bridge): support special letters in line protocol for influxDB (WIP)

---

src/i18n/Extension.js
src/i18n/RuleEngine.js
src/i18n/Tools.js
src/views/Base/LeftBar.vue
src/views/Config/Extension/components/rewrite.vue
src/views/Diagnose/TopicMetrics.vue
src/views/Diagnose/components/WebSocketItem.vue
src/views/Retained/Retained.vue

fix(src): translation enhancement

---

src/hooks/useChangePwdGuide.ts
src/views/RuleEngine/components/CopySubmitDialog.vue

The same fixes have been synced to enterprise and open source 4.*

fix(change pwd guide): close message box when route leave

---

src/views/Settings/Help.vue

https://user-images.githubusercontent.com/26165221/206374223-04fdb3b0-e73c-4f74-8a0b-e13a60c664ee.mov

fix(help): fixed style issues

---

src/components/SchemaForm.tsx
src/hooks/Rule/bridge/useRedisSecondTypeControl.ts
src/hooks/Rule/bridge/useSyncConfiguration.ts
src/hooks/useFillNewRecord.ts
src/views/RuleEngine/Bridge/BridgeCreate.vue
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/Components/UsingSchemaBridgeConfig.vue

https://user-images.githubusercontent.com/26165221/207828298-e819dcfc-6a0a-4c96-84d4-6fea7a70e4f7.mov

feat(bridge): supported use select to control bridge form

---

src/components/InfoTooltip.vue
src/components/SchemaForm.tsx

style(info tooltip): use margin replace with positive

---

src/components/TLSConfig/TLSBaseConfig.vue
src/i18n/Base.js
src/i18n/Gateway.js
src/i18n/RuleEngine.js
src/views/RuleEngine/Bridge/Components/MQTTBridgeTransConfiguration.vue
src/views/RuleEngine/components/RuleOutputsDrawer.vue
src/views/RuleEngine/components/SQLTest.vue

fix(rule): change retain to flags.retain

---

src/i18n/Extension.js
src/views/Config/BasicConfig/Retainer.vue
src/views/RuleEngine/Bridge/BridgeCreate.vue

feat(retainer config): add desc for each form item

---

src/components/TLSConfig/TLSBaseConfig.vue
src/i18n/RuleEngine.js
src/style/rule.scss
src/types/rule.d.ts
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeHttpConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeMqttConfig.vue
src/views/RuleEngine/Bridge/Components/MQTTBridgeTransConfiguration.vue
src/views/RuleEngine/Connector/ConnectorMqttConfig.vue

refactor(mqtt): on-demand ingress/egress configs

---

src/common/constants.ts
src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Rule/bridge/useSecondTypeControl.ts
src/i18n/RuleEngine.js
src/views/RuleEngine/Bridge/Components/UsingSchemaBridgeConfig.vue

feat(bridge): add mongo

---

src/api/common.ts
src/common/docLinks.ts
src/i18n/Dashboard.js
src/store/index.ts
src/types/dashboard.d.ts
src/types/enum.ts
src/views/Base/Layout.vue
src/views/Dashboard/Overview.vue
src/views/Dashboard/components/LicenseCard.vue
src/views/Dashboard/components/LicenseUpdateDialog.vue

feat(overview): show license info and update license

---

src/i18n/Dashboard.js
src/views/Base/Layout.vue
src/views/Base/LicenseTipDialog.vue
src/views/Dashboard/components/LicenseCard.vue

feat(layout): license warning dialog

---

src/components/TLSConfig/CommonTLSConfig.vue
src/components/TLSConfig/TLSEnableConfig.vue
src/i18n/RuleEngine.js
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue

feat(bridge): add kafka sni description

---

src/components/SchemaForm.tsx
src/hooks/Rule/bridge/useBridgeDataHandler.ts

& changed order of execution of some statements

refactor(schema form & bridge): judge bridge type when handle bridge data

---

src/views/Base/LeftBar.vue

https://user-images.githubusercontent.com/26165221/212863242-12db4d88-3d2e-427a-9df3-f76256f104c8.mov
fixed this

style(left bar): set title `white-space` to `nowrap`

---

src/hooks/Overview/useDrawNodesGraph.ts

fix(overview): layout of nodes graph

---

src/common/tools.ts
src/common/utils.js
src/components/TargetDetailMetrics.vue
src/views/Dashboard/Overview.vue

refactor(bridge): optimized styles to perform better on small resolution

---

src/hooks/Rule/bridge/useInfluxdbFieldsEditor.ts
src/i18n/RuleEngine.js
src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbFieldsEditor.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbLineProtocolForm.vue

refactor(bridge influxdb): show tip when fill field value

---

src/i18n/BasicConfig.js
src/views/Dashboard/Overview.vue
src/views/Dashboard/components/RateChart.vue

https://user-images.githubusercontent.com/26165221/217472889-ff1fa30d-9d21-406c-8579-b10b067858c2.mov

refactor(overview): optimize tooltip when chart has no data

---

src/views/Dashboard/components/RateChart.vue

style(overview): color of no data text

---

public/static/hot-config-schema-en.json
public/static/hot-config-schema-zh.json
src/common/highlight/sql.js
src/components/SchemaForm.tsx
src/i18n/Auth.js
src/i18n/Base.js
src/i18n/Clients.js
src/i18n/Dashboard.js
src/i18n/Gateway.js
src/i18n/General.js
src/i18n/RuleEngine.js
src/style/common.scss
src/style/normalize.scss
src/views/Auth/AuthnCreate.vue
src/views/Auth/AuthnDetails.vue
src/views/Auth/components/AuthItemOverview.vue
src/views/Dashboard/Overview.vue
src/views/Diagnose/TopicMetrics.vue

Found via `typos --format brief`.

Fix typos in project

---

src/i18n/Auth.js
src/style/common.scss
src/views/Auth/components/AuthnManager.vue

refactor(auth): add description for is_superuser

---

src/components/SchemaForm.tsx
src/style/normalize.scss
src/style/schemaForm.scss

https://user-images.githubusercontent.com/26165221/219605814-ef3aaad6-81a0-4758-9ffe-d168e63a7c51.mov
As before, if you think it looks better and the code is fine you can merge this PR, otherwise you can close it

refactor(schema): try to optimize the schema loading effect

---

src/i18n/MonitoringIntegration.js

fix(i18n): escape special characters

---

src/components/Oneof.vue

close it if you think this is wrong

refactor(oneof): try to optimize `isJSONString`

---

src/components/SchemaForm.tsx
src/hooks/Config/useSchemaForm.ts

I will merge into the dev branch after the release of the enterprise version.
The real loading completion time point is very easy to find, but I think it is too complicated; but by the way, I have optimized a little bit of rendering efficiency.

refactor(schema form): try to optimize and loading status

---

src/style/normalize.scss

style(client): curious scroll bar within the table

---

src/components/MarkdownContent.vue
src/components/SchemaForm.tsx
src/style/schemaForm.scss

refactor(schema): use markdown content to show desc

---

src/style/normalize.scss
src/views/Dashboard/NodeDetail.vue
src/views/Dashboard/Nodes.vue
src/views/Dashboard/components/NodesGraphCard.vue

styles(nodes): modify the progress text display

---

src/style/common.scss
src/style/themes/dark.scss
src/style/themes/light.scss
src/views/Auth/AuthnDetails.vue
src/views/Auth/AuthzDetails.vue
src/views/Config/Monitoring/MonitoringIntegration.vue
src/views/Config/Monitoring/components/HelpDrawer.vue
src/views/Diagnose/WebSocket.vue
src/views/Exhook/ExhookDetail.vue
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeHttpConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeMqttConfig.vue
src/views/RuleEngine/IoT/IoTDetail.vue

refactor(details): update the details page header

---

src/i18n/RuleEngine.js
src/style/common.scss
src/views/Gateway/components/listeners.vue
src/views/RuleEngine/Bridge/BridgeDetail.vue

styles(common): style optimizations

---

src/hooks/Schema/useItemLabelAndDesc.ts

To avoid warnings in the console

refactor(schema): add label for enable and type

---

src/i18n.ts
src/schemaText/resource-opt-schema-en.json
src/schemaText/resource-opt-schema-zh.json

Because the MQTT bridge and Webhook are also in use

refactor(schema text): add resource opt

---

src/hooks/Rule/bridge/useResourceOpt.ts
src/i18n/RuleEngine.js
src/types/rule.d.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeResourceOpt.vue

- Rename `async_inflight_window` to `inflight_window`
- Get label and desc from local

refactor(bridge): resource opt

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Rule/bridge/useSyncConfiguration.ts

refactor(bridge): rename `async_inflight_window`

---

.env.development
.env.enterprise
README.md
package.json

And make corresponding modifications in the README
I'm not sure if this is correct, please review

chore(package.json): remove `--mode`

---

src/hooks/Rule/bridge/useResourceOpt.ts
src/types/rule.d.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeResourceOpt.vue

refactor(bridge): rename `max_queue_bytes`

---

src/hooks/useI18nTl.ts
src/i18n/Base.js
src/i18n/RuleEngine.js
src/schemaText/bridge-text-zh.json
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/KafkaProducerConfig.vue

https://emqx.atlassian.net/browse/ED-630
https://emqx.atlassian.net/browse/ED-628

fix(bridge): fix wrong desc

---

src/hooks/Schema/useItemLabelAndDesc.ts
src/hooks/Schema/useSchemaForm.ts
src/i18n/BasicConfig.js
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/views/Config/BasicConfig/Log.vue

https://emqx.atlassian.net/browse/ED-629

refactor(log): adapt to new log

---

src/hooks/Schema/useItemLabelAndDesc.ts
src/i18n/BasicConfig.js
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/views/Config/BasicConfig/Log.vue

This reverts commit f04addee224b2a931e4a42528bcf5fc9c39ff78f.

Revert "refactor(log): adapt to new log"

---

src/components/CustomInputNumber.vue
src/components/Oneof.vue
src/components/SchemaForm.tsx
src/views/Auth/components/AuthzSettingDrawer.vue
src/views/Auth/components/HttpConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeHttpConfig.vue

https://emqx.atlassian.net/browse/ED-613

refactor(global): add `CustomInputNumber`

---

src/components/ListenerDrawer/ListenerDrawer.vue

https://emqx.atlassian.net/browse/ED-608

refactor(listener): show `password` field for QUIC

---

src/views/RuleEngine/Bridge/Components/BridgeItemOverview.vue

https://emqx.atlassian.net/browse/ED-606

refactor(bridge): show egress data as `-`

---

src/hooks/Rule/bridge/useResourceOpt.ts
src/types/rule.d.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeHttpConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeResourceOpt.vue

refactor(bridge http): remove duplicated field

---

src/components/Oneof.vue
src/hooks/useFormRules.ts
src/views/AdvancedMQTT/DelayedPub.vue

https://emqx.atlassian.net/browse/ED-552

fix(delayed pub): add rule to form

---

src/api/ruleengine.ts
src/hooks/Rule/schema/useSchemaType.ts
src/i18n/Base.js
src/i18n/RuleEngine.js
src/i18n/components.js
src/router/index.ts
src/types/enum.ts
src/types/rule.d.ts
src/views/Base/LeftBar.vue
src/views/RuleEngine/Schema/Schema.vue
src/views/RuleEngine/Schema/SchemaCreate.vue
src/views/RuleEngine/Schema/SchemaDetail.vue
src/views/RuleEngine/Schema/components/SchemaRegistryForm.vue
src/views/RuleEngine/Schema/components/TableItemDropdown.vue

https://emqx.atlassian.net/browse/ED-549

feat(schema): add schema registry

---

src/hooks/useFormRules.ts
src/i18n/Rule.js
src/schemaText/resource-opt-schema-en.json

https://emqx.atlassian.net/browse/ED-621

fix(form rule): error msg when label has no value

---

src/i18n/Rule.js

https://emqx.atlassian.net/browse/ED-619

fix(config): update error tip

---

src/i18n/RuleEngine.js
src/schemaText/schema-text-en.json
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeResourceOpt.vue
src/views/RuleEngine/components/RuleOutputs.vue

https://emqx.atlassian.net/browse/ED-619
https://emqx.atlassian.net/browse/ED-626
https://emqx.atlassian.net/browse/ED-624

fix(schema): update i18n

---

src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-624

fix(bridge): update username/password translation

---

src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-636

fix(bridge): some text error on RabbitMQ bridge

---

src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json
src/views/RuleEngine/Schema/components/SchemaRegistryForm.vue

https://emqx.atlassian.net/browse/ED-645

fix(schema): add pattern for `name` field

---

src/schemaText/bridge-text-en.json

https://emqx.atlassian.net/browse/ED-632

fix(bridge): update oracle ii18n

---

src/components/Oneof.vue
src/components/commonPagination.vue
src/hooks/usePaginationRemember.ts
src/i18n/Auth.js
src/views/Auth/Authn.vue
src/views/Auth/Authz.vue

https://emqx.atlassian.net/browse/ED-659

refactor(one of): set default unit on time input

---

src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgePulsarConfig.vue

Related change: https://github.com/emqx/emqx/pull/10757

feat(pulsar): add `connect_timeout` config parameter

---

src/views/Config/Monitoring/MonitoringIntegration.vue

https://emqx.atlassian.net/browse/ED-668

style(monitor): set span correspondingly

---

src/hooks/Rule/bridge/useInfluxdbLineProtocol.ts

https://emqx.atlassian.net/browse/ED-537

fix(bridge influxdb): regex for line protocol

---

package.json
src/common/tools.ts
src/hooks/Rule/bridge/useBridgeDataHandler.ts
yarn.lock

Fixes: https://emqx.atlassian.net/browse/EMQX-9546

refactor(bridge http): do not encode/decode body

---

src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgePulsarConfig.vue

https://emqx.atlassian.net/browse/ED-688

fix(bridge pulsar): form had no value when editing

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/hooks/Config/useListenerDialog.ts
src/hooks/Config/useListenerUtils.ts
src/i18n/Gateway.js

https://emqx.atlassian.net/browse/ED-662

refactor(listener): optimize limiter config

---

src/i18n/Extension.js
src/types/extension.d.ts
src/views/Config/BasicConfig/Retainer.vue
src/views/Config/BasicConfig/Session.vue

https://emqx.atlassian.net/browse/ED-689
https://emqx.atlassian.net/browse/ED-690

refactor(retainer): add `deliver_rate`

---

src/api/clients.ts
src/i18n/Clients.js
src/views/Clients/Clients.vue

https://emqx.atlassian.net/browse/ED-701

refactor(client): use batch kick out API

---

src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgePulsarConfig.vue

https://emqx.atlassian.net/browse/ED-706

refactor(bridge pulsar): update resource opt

---

package.json
src/hooks/Overview/useNodesGraph.ts
src/views/Dashboard/Overview.vue
src/views/Dashboard/components/BackgroundCircle.vue
src/views/Dashboard/components/CoreNode.vue
src/views/Dashboard/components/NodesGraph.vue
src/views/Dashboard/components/NodesGraphCard.vue
src/views/Dashboard/components/RepNode.vue
vue.config.js
yarn.lock

Supported display with only core nodes

refactor(overview): new nodes topology (WIP)

---

src/i18n/RuleEngine.js
src/types/rule.d.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeMqttConfig.vue

https://emqx.atlassian.net/browse/ED-691

refactor(bridge mqtt): add `pool_size`

---

src/components/ListenerDrawer/ListenerDrawer.vue

https://emqx.atlassian.net/browse/ED-699

fix(listener): no display max connection rate in ws/wss

---

src/views/Dashboard/components/BackgroundCircle.vue
src/views/Dashboard/components/CoreNode.vue
src/views/Dashboard/components/NodesGraph.vue

https://emqx.atlassian.net/browse/ED-58

style(overview): color of nodes topology

---

src/i18n/Dashboard.js
src/views/Dashboard/Overview.vue

https://emqx.atlassian.net/browse/ED-495

feat(overview): add `live_connections`

---

src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/i18n/RuleEngine.js

https://emqx.atlassian.net/browse/ED-744

refactor(bridge): rename webhook to http

---

src/assets/topologyIcon/index.ts
src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/views/Dashboard/components/NodesCountCard.vue

https://emqx.atlassian.net/browse/ED-744

style(overview): width of nodes count card

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts

Related PR: https://github.com/emqx/emqx/pull/10995

fix(iotdb): remove `request_timeout` field

---

src/views/Gateway/components/exprotoBasic.vue

https://emqx.atlassian.net/browse/ED-713

fix(exproto): fix grpc adapter bind defaut value

---

src/views/Gateway/components/stompBasic.vue

https://emqx.atlassian.net/browse/ED-704

fix(stomp): max-body-length add limit rule

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/hooks/Config/useListenerDialog.ts
src/hooks/Config/useListenerUtils.ts

https://emqx.atlassian.net/browse/ED-703

fix(listener): flexible decision certfile required

---

src/hooks/Auth/useJWTConfigForm.ts
src/schemaText/schema-text-zh.json
src/views/Auth/components/DatabaseConfig.vue
src/views/Auth/components/HttpConfig.vue
src/views/Auth/components/JwtConfig.vue

https://emqx.atlassian.net/browse/ED-735
https://emqx.atlassian.net/browse/ED-734
https://emqx.atlassian.net/browse/ED-710

fix(jwt): set public key to required field

---

src/views/RuleEngine/Bridge/BridgeDetail.vue

https://emqx.atlassian.net/browse/ED-741

fix(bridge): repeatedly warn need to re-enter pwd

---

src/hooks/Rule/bridge/useBridgeDataHandler.ts
src/hooks/Rule/bridge/useComponentsHandlers.ts

Because I haven't fully completed the content of the related card, I didn't post a link; there are some details that need to be confirmed with QA.

fix(bridge): for pwd-like fields, hide when editing

---

src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgePulsarConfig.vue

https://emqx.atlassian.net/browse/ED-737

fix(pulsar): encrypted display jwt

---

src/hooks/Auth/useDatabaseConfigForm.ts
src/i18n/Auth.js
src/i18n/AuthDoc.js
src/views/Auth/components/DatabaseConfig.vue

https://emqx.atlassian.net/browse/ED-714

fix(auth): modified some translations and fields in mongodb

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgePulsarConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/KafkaProducerConfig.vue

https://emqx.atlassian.net/browse/ED-745
https://emqx.atlassian.net/browse/ED-739

refactor(bridge kafka): add two new fields

---

src/views/Gateway/components/clients.vue

https://emqx.atlassian.net/browse/ED-715

fix(gateway): hide username in mqtt-sn

---

src/views/Gateway/components/clients.vue

https://emqx.atlassian.net/browse/ED-715

fix(gateway): hide user name in search bar

---

src/hooks/Rule/bridge/useBridgeDataHandler.ts

https://emqx.atlassian.net/browse/ED-750

fix(bridge): check before set to empty value

---

src/components/ListenerDrawer/ListenerDrawer.vue

https://emqx.atlassian.net/browse/ED-755

fix(listener): translate unit of limiter conf

---

src/components/ListenerDrawer/ListenerDrawer.vue

https://emqx.atlassian.net/browse/ED-748

fix(listener): hide Max Connection Rate for QUIC

---

src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/KafkaConsumerConfig.vue

https://emqx.atlassian.net/browse/EMQX-10199?focusedCommentId=29331

refactor(bridge kafka): adapting change on backend

---

src/views/Base/LeftBar.vue

refactor(menu): adjust the order of menu items

---

src/components/SchemaForm.tsx
src/hooks/Schema/useSchemaForm.ts
src/views/Config/BasicConfig/Mqtt.vue
src/views/Config/BasicConfig/Session.vue

refactor(schema form): accept an array as `ref`

---

src/i18n/RuleEngine.js

https://emqx.atlassian.net/browse/ED-691

fix(bridge mqtt): desc of `pool_size`

---

src/hooks/Rule/bridge/useSyncConfiguration.ts

https://emqx.atlassian.net/browse/ED-759

fix(bridge): func to cal whether to show field

---

src/hooks/Overview/useNodesGraph.ts
src/views/Dashboard/components/NodesGraph.vue

https://emqx.atlassian.net/browse/ED-760

fix(overview): style issue after joining nodes

---

src/components/SchemaForm.tsx

https://emqx.atlassian.net/browse/ED-763

refactor(schema): remove rules for concise SSL

---

src/i18n/Dashboard.js
src/i18n/RuleEngine.js

https://emqx.atlassian.net/browse/ED-764

fix(overview): fix metrics desc typo

---

src/hooks/Config/useListenerUtils.ts
src/i18n/components.js

https://emqx.atlassian.net/browse/ED-773

fix(integration): bridge -> bridges

---

src/i18n/Base.js
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-769

Fix EE bugs

---

src/store/index.ts

https://emqx.atlassian.net/browse/ED-772

feat(store): update default lang setting

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/i18n/General.js
src/i18n/components.js
src/router/index.ts
src/views/Base/LeftBar.vue
src/views/General/FlappingDetect.vue

https://emqx.atlassian.net/browse/ED-716

feat(access): add flapping detect config page

---

src/i18n/RuleEngine.js

https://emqx.atlassian.net/browse/ED-782

fix(rule): update unknow desc

---

src/i18n/Dashboard.js

https://emqx.atlassian.net/browse/ED-774

fix(overview): fix message rate unit

---

src/views/Dashboard/components/LicenseCard.vue

https://emqx.atlassian.net/browse/ED-767

fix(overview): fix license usage display issue

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts

See https://github.com/emqx/emqx/pull/11163

fix(mongo): remove `topology.pool_size`

---

src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/views/RuleEngine/Bridge/Components/UsingSchemaBridgeConfig.vue

https://emqx.atlassian.net/browse/ED-794

fix(bridge): fix can not show the pubsub config page

---

src/components/ObjectArrayEditor.vue
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/KafkaProducerConfig.vue

https://emqx.atlassian.net/browse/ED-792

feat(kafka): adapt the kafka headers

---

src/views/Gateway/components/lwm2mBasic.vue

https://emqx.atlassian.net/browse/EMQX-10306
question 2

fix(gateway): default value for some fields

---

package.json
src/components/EMQXVersion.vue
src/hooks/useClusterNodes.ts
src/i18n/Dashboard.js
src/store/index.ts
src/views/Base/Layout.vue
src/views/Dashboard/components/NodesGraphCard.vue
yarn.lock

feat(leftbar): show emqx version in the leftbar

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-308

refactor(bridge HStream): adapting field changes

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/components/TLSConfig/TLSEnableConfig.vue

https://emqx.atlassian.net/browse/ED-801

refactor(listener): do not require verify

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/components/TLSConfig/TLSEnableConfig.vue
src/components/TextareaWithUploader.vue
src/style/normalize.scss
src/views/Config/BasicConfig/Retainer.vue

https://emqx.atlassian.net/browse/ED-803
https://emqx.atlassian.net/browse/ED-801
https://emqx.atlassian.net/browse/ED-804

fix(retainer): disable all form items

---

src/i18n/components.js

https://emqx.atlassian.net/browse/ED-791

fix(license): update linecse name

---

src/api/common.ts
src/i18n/Dashboard.js
src/style/common.scss
src/style/normalize.scss
src/types/dashboard.d.ts
src/views/General/License.vue

https://emqx.atlassian.net/browse/ED-791

feat(license): support license config

---

src/i18n/Extension.js
src/types/extension.d.ts
src/views/Config/BasicConfig/Retainer.vue

https://emqx.atlassian.net/browse/ED-809

refactor(retainer): sync fields changed from back end

---

src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/EMQX-10532

fix(bridge HStream): completed some desc

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts

https://emqx.atlassian.net/browse/ED-807

fix(bridge GCP): fixed fields order

---

src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-783

fix(bridge): change the desc for timescale and matrix

---

src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-815

fix(bridge HStream): modify label for field

---

src/components/CustomInputNumber.vue

https://emqx.atlassian.net/browse/ED-814

fix(components): fix can type string in the number input

---

src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://github.com/emqx/emqx/pull/11285/files
sync

refactor(bridge HStream): sync desc from backend

---

src/views/General/License.vue

https://emqx.atlassian.net/browse/ED-817

feat(license): implement watermark tooltip

---

src/views/Base/Layout.vue

i am not sure this is right, please confirm

style(layout): add wrapper for router-view

---

package.json
src/common/http.js
src/hooks/useSyncPolling.ts
src/router/index.ts
src/store/index.ts
yarn.lock

https://emqx.atlassian.net/browse/ED-818

feat(login): support cancel request when logout

---

src/store/index.ts

https://emqx.atlassian.net/browse/ED-826

fix(setting): set sync os theme by default

---

src/hooks/Rule/bridge/useSpecialRuleForPassword.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeMqttConfig.vue

refactor(bridge): rename `ruleWhenTestConnection`

---

src/hooks/Rule/bridge/useBridgeDataHandler.ts

https://emqx.atlassian.net/browse/ED-862

fix(bridge): set role to GCP after loaded

---

src/hooks/Auth/useAuthnCreate.ts
src/hooks/Auth/useAuthzCreate.ts
src/views/Auth/AuthzCreate.vue
src/views/Auth/AuthzDetails.vue
src/views/Auth/components/LdapConfig.vue

https://emqx.atlassian.net/browse/ED-857

feat(auth): add ldap authz

---

src/hooks/Flow/useReuseBridgeInFlow.ts
src/views/Flow/components/NameInputForCopyBridgeDialog.vue
src/views/Flow/components/form/MQTTBrokerForm.vue

in `NameInputForCopyBridgeDialog`

fix(flow): emit name when save

---

src/hooks/Flow/useFlowNode.ts
src/hooks/Flow/useReuseBridgeInFlow.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeInfluxdbConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgePulsarConfig.vue
src/views/RuleEngine/Bridge/Components/UsingSchemaBridgeConfig.vue

refactor(flow): adapted function modifications in

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts

https://emqx.atlassian.net/browse/ED-879

refactor(bridge): remove TLS for GreptimeDB

---

src/hooks/Flow/useNodeDrawer.ts
src/views/Flow/components/NodeDrawer.vue
src/views/Flow/components/form/MQTTBrokerForm.vue
src/views/Webhook/components/Trigger.vue
src/views/Webhook/components/WebhookForm.vue

https://emqx.atlassian.net/browse/ED-875
https://emqx.atlassian.net/browse/ED-876

style(flow): adjust some style by design

---

src/hooks/Rule/bridge/useBridgeDataHandler.ts

https://emqx.atlassian.net/browse/ED-872

fix(bridge): delete `id` and `enable` when duplicate bridge

---

src/hooks/Flow/useEditFlow.ts
src/hooks/Flow/useFlowEdge.ts
src/hooks/Flow/useFlowEditorDataHandler.ts
src/hooks/Flow/useFlowView.ts
src/hooks/Flow/useGenerateFlowDataUtils.ts
src/i18n/Flow.js
src/views/Flow/components/FlowEditor.vue

https://emqx.atlassian.net/browse/ED-883
https://emqx.atlassian.net/browse/ED-894
https://emqx.atlassian.net/browse/ED-895

fix(flow): try to optimize the layout

---

src/views/Flow/components/FlowEditor.vue

https://emqx.atlassian.net/browse/ED-897

fix(flow): set `isCreated` just by id

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json
src/views/RuleEngine/Bridge/Components/BridgeConfig/KafkaProducerConfig.vue

https://emqx.atlassian.net/browse/ED-902
https://emqx.atlassian.net/browse/ED-904

fix(bridge): value displayed of query_mode in kafka bridge

---

src/components/ObjectArrayEditor.vue
src/components/SchemaForm.tsx
src/views/Flow/components/FlowEdge.vue
src/views/Flow/components/FlowEditor.vue

https://emqx.atlassian.net/browse/ED-890

feat(flow): add interaction for del edge

---

src/components/KeyAndValueEditor.vue

https://emqx.atlassian.net/browse/ED-909

fix(webhook): unchangeable `headers`

---

src/hooks/Rule/bridge/useBridgeFormCreator.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue

https://emqx.atlassian.net/browse/ED-906

refactor(bridge): adapt `health_check_interval` in bridge kafka

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-881
https://emqx.atlassian.net/browse/ED-873

fix(bridge): update greptimedb i18n

---

src/i18n/MonitoringIntegration.js
src/views/Auth/components/LdapConfig.vue
src/views/Flow/FlowHandler.vue

https://emqx.atlassian.net/browse/ED-910
https://emqx.atlassian.net/browse/ED-911
https://emqx.atlassian.net/browse/ED-887
https://emqx.atlassian.net/browse/ED-889

fix(ldap): update base dn placeholder

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-864
https://emqx.atlassian.net/browse/ED-905
https://emqx.atlassian.net/browse/ED-916
https://emqx.atlassian.net/browse/ED-874

fix(bridge): update mongodb field

---

src/common/tools.ts
src/hooks/Flow/useGenerateFlowDataUtils.ts
src/hooks/Flow/useParseWhere.ts
src/i18n/Flow.js
src/views/Flow/components/NodeDrawer.vue
src/views/Flow/components/form/processing/FilterForm.vue
src/views/Flow/components/form/processing/FunctionBlock.vue
src/views/Flow/components/form/processing/FunctionForm.vue

https://emqx.atlassian.net/browse/ED-861
Specifically
- FOREACH syntax is used
- Nested functions are used
- the function used does not support presentation in form (e.g. sprintf)
- the filter level is more than 2

feat(flow): complex filters will switch to SQL editing

---

src/views/Flow/FlowHandler.vue

https://emqx.atlassian.net/browse/ED-903

fix(flow): add back btn for detail page

---

package.json

doc(package): update version for right doc link

---

src/views/Webhook/components/WebhookForm.vue

https://emqx.atlassian.net/browse/ED-927

fix(webhook): add rule for `pool_size`

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/schemaText/symbol-label-en.json
src/schemaText/symbol-label-zh.json
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeInfluxdbConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgePulsarConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbFieldsEditor.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbLineProtocolForm.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbWriteSyntaxInput.vue

https://emqx.atlassian.net/browse/ED-880
https://emqx.atlassian.net/browse/ED-908
https://emqx.atlassian.net/browse/ED-884
https://emqx.atlassian.net/browse/ED-925
https://emqx.atlassian.net/browse/ED-928

fix(bridge): add label for `precision` opt

---

src/components/KeyAndValueEditor.vue
src/hooks/Flow/useEditFlow.ts
src/hooks/Flow/useFlowView.ts
src/hooks/Flow/useGenerateFlowDataUtils.ts
src/hooks/Flow/useNodeDrawer.ts
src/i18n/Flow.js
src/views/Flow/components/NodeDrawer.vue
src/views/Flow/components/form/MQTTBrokerForm.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeHttpConfig.vue
src/views/RuleEngine/components/RemovedBridgeTip.vue

https://emqx.atlassian.net/browse/ED-886

fix(flow): add missing node drawer title

---

src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-923

fix(bridge): update azure connection string

---

src/hooks/Webhook/useWebhookList.ts
src/views/Webhook/Webhook.vue

https://emqx.atlassian.net/browse/ED-920

feat(webhook): support delete webhook

---

src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-931

fix(bridge): update kafka header desc

---

src/components/AdvancedSettingsBtn.vue
src/components/SchemaForm.tsx
src/style/normalize.scss
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeHttpConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeMqttConfig.vue

https://emqx.atlassian.net/browse/ED-907

feat(schema): support hide advanced setting in schema

---

src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-882

fix(bridge): update influxdb i18n

---

src/router/index.ts
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/Webhook/Webhook.vue

https://emqx.atlassian.net/browse/ED-921

fix(webhook): add detail stats page

---

src/components/AdvancedSettingsBtn.vue
src/types/rule.d.ts
src/views/Flow/components/form/MQTTBrokerForm.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeHttpConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeMqttConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/ConnectorMqttConfig.vue

refactor(bridge): set advanced fields by table

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgePulsarConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/KafkaConsumerConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/KafkaProducerConfig.vue
src/views/RuleEngine/Bridge/Components/UsingSchemaBridgeConfig.vue

https://emqx.atlassian.net/browse/ED-938

refactor(bridge): for pulsar, set fields to advanced settings by table

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts

https://emqx.atlassian.net/browse/ED-939

style(bridge): `username` field position in redis bridge

---

src/common/tools.ts
src/components/SchemaForm.tsx
src/hooks/Config/useListenerDialog.ts
src/hooks/Config/useListenerUtils.ts
src/hooks/Schema/useItemLabelAndDesc.ts
src/views/Flow/components/NodeDrawer.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/ConnectorMqttConfig.vue

https://emqx.atlassian.net/browse/ED-736

refactor(listener): do not remove file fields when update

---

src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgePulsarConfig.vue
src/views/RuleEngine/Bridge/Components/UsingSchemaBridgeConfig.vue

https://emqx.atlassian.net/browse/ED-935

fix(flow): emit record init event to node drawer

---

src/hooks/Flow/useFlowNode.ts
src/hooks/Flow/useGenerateFlowDataUtils.ts
src/views/Flow/components/FlowEditor.vue
src/views/Flow/components/NameInputForCopyBridgeDialog.vue
src/views/Flow/components/NodeDrawer.vue

https://emqx.atlassian.net/browse/ED-940

fix(flow): new save as a new sink/source

---

src/hooks/useDataNotSaveConfirm.ts
src/views/Flow/FlowHandler.vue
src/views/Flow/components/form/processing/FunctionBlock.vue

https://emqx.atlassian.net/browse/ED-947
https://emqx.atlassian.net/browse/ED-948

fix(flow): set required to `alias` after calling func

---

src/views/Flow/components/FlowEditor.vue
src/views/Flow/components/NodeDrawer.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/ConnectorMqttConfig.vue

https://emqx.atlassian.net/browse/ED-950
https://emqx.atlassian.net/browse/ED-944

fix(flow): new save as a new sink/source when creating node

---

src/views/RuleEngine/Bridge/BridgeDetail.vue

https://emqx.atlassian.net/browse/ED-942

fix(webhook): fix webhook name in stats page

---

src/components/InputSelect.vue
src/i18n/RuleEngine.js
src/views/Flow/components/NodeDrawer.vue
src/views/RuleEngine/IoT/IoT.vue

https://emqx.atlassian.net/browse/ED-955
https://emqx.atlassian.net/browse/ED-946
https://emqx.atlassian.net/browse/ED-951

fix(rule): show action count

---

src/api/function.ts
src/i18n/General.js
src/views/General/BannedClient.vue

https://emqx.atlassian.net/browse/ED-959

feat(banned): support clear all banned clients

---

src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/i18n/RuleEngine.js
src/views/RuleEngine/Bridge/BridgeCreate.vue

https://emqx.atlassian.net/browse/ED-958

feat(bridge): support search filter

---

src/views/RuleEngine/Bridge/BridgeCreate.vue

https://emqx.atlassian.net/browse/ED-967

fix(bridge): disable the next button when search birdge is empty

---

.github/workflows/sync_code_to_.yaml

https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow

chore(sync): use personal token

---

src/common/http.js

https://emqx.atlassian.net/browse/ED-932

fix(log trace): processing return data of type blob

---

src/hooks/Flow/useFlowView.ts
src/hooks/Flow/useParseWhere.ts

https://emqx.atlassian.net/browse/ED-968

fix(flow): catch sing error when generate nodes

---

src/router/index.ts

https://emqx.atlassian.net/browse/ED-970

fix(router): fix login expired msg on dashboard load

---

src/hooks/useFormRules.ts
src/i18n/Rule.js
src/views/Flow/components/form/MQTTBrokerForm.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeMqttConfig.vue

https://emqx.atlassian.net/browse/ED-973

feat(bridge): enhance MQTT topic validation

---

src/views/RuleEngine/Schema/components/SchemaRegistryForm.vue

https://emqx.atlassian.net/browse/ED-918

fix(schema): prompted message doesn't disappear after inputting required field

---

src/i18n/Base.js
src/style/normalize.scss

https://emqx.atlassian.net/browse/ED-971

fix(base): refine commonIdError message for clarity

---

src/style/common.scss
src/views/Dashboard/components/NodeListPopover.vue
src/views/Flow/components/FlowEdge.vue
src/views/Flow/components/FlowEditor.vue
src/views/Flow/components/FlowGuideNode.vue
src/views/Flow/components/form/processing/FilterItemReadonly.vue
src/views/Flow/components/form/processing/FilterOperatorLineReadonly.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeHttpConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeResourceOpt.vue

https://emqx.atlassian.net/browse/ED-936
https://emqx.atlassian.net/browse/ED-937
https://emqx.atlassian.net/browse/ED-930

fix(bridge): pool_size is not required

---

src/api/common.ts
src/hooks/SSO/useSSO.ts
src/router/index.ts
src/store/index.ts
src/views/Base/Login.vue
src/views/Base/NavHeader.vue

https://emqx.atlassian.net/browse/ED-977

feat(logout): add logout API

---

.github/workflows/build_emqx_for_test.yaml
orval.config.ts
package.json
src/common/constants.ts
src/common/http.js
src/style/normalize.scss
src/types/schemas/configs.schemas.ts
src/types/schemas/dashboard.schemas.ts
src/views/Webhook/WebhookCreate.vue

https://emqx.atlassian.net/browse/ED-960

chore(ci): use release-53 branch to build emqx

---

orval.config.ts

I forgot that CI will use the `BASE_URL` ..

chore(orval): get BASE_URL when creating schema

---

src/views/General/SSO.vue
src/views/General/SSODetail.vue

https://emqx.atlassian.net/browse/EMQX-11035

fix(sso): do not get info from route query

---

src/hooks/Schema/useItemLabelAndDesc.ts
src/i18n/BasicConfig.js
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json

https://emqx.atlassian.net/browse/ED-979

fix(conf): add text for audit log

---

src/api/function.ts
src/types/schemas/configs.schemas.ts
src/views/General/Users.vue

https://emqx.atlassian.net/browse/ED-987

fix(user): pass the `backend` parameter correctly

---

src/views/RuleEngine/components/RePubForm.vue
src/views/RuleEngine/components/RuleOutputsDrawer.vue

https://emqx.atlassian.net/browse/ED-981

fix(rule): add topic validation for republish

---

src/views/Diagnose/TopicMetrics.vue
src/views/Diagnose/components/SlowSubData.vue
src/views/Flow/components/NodeDrawer.vue
src/views/RuleEngine/IoT/components/RuleItemOverview.vue
src/views/RuleEngine/components/RuleOutputs.vue
src/views/RuleEngine/components/SQLTest.vue
src/views/RuleEngine/components/TableItemDropDown.vue

https://emqx.atlassian.net/browse/ED-985
https://emqx.atlassian.net/browse/ED-986
https://emqx.atlassian.net/browse/ED-988
https://emqx.atlassian.net/browse/ED-990

fix(rule): add permission check for rule overview

---

src/views/RuleEngine/Bridge/Components/BridgeItemOverview.vue

https://emqx.atlassian.net/browse/ED-985

fix(bridge): add perms check for slow bridge overview

---

src/i18n/General.js
src/types/schemas/configs.schemas.ts
src/types/schemas/listeners.schemas.ts

https://emqx.atlassian.net/browse/ED-991

fix(sso): desc error

---

src/views/Dashboard/components/PolylineChart.vue

https://emqx.atlassian.net/browse/ED-974

fix(overview): display seconds in time string

---

src/types/schemas/dashboardSingleSignOn.schemas.ts
src/views/General/SSODetail.vue
src/views/General/components/SSOForm/LDAPForm.vue
src/views/General/components/SSOForm/SAMLForm.vue

https://emqx.atlassian.net/browse/ED-994

fix(sso): key file input box should be in the editing state when editing

---

src/hooks/Flow/useNodeForm.ts
src/i18n/RuleEngine.js
src/types/rule.d.ts
src/views/Flow/components/NodeDrawer.vue
src/views/RuleEngine/components/RePubForm.vue
src/views/RuleEngine/components/RuleOutputsDrawer.vue

https://emqx.atlassian.net/browse/ED-972

refactor(rule): reuse re pub form in outputs drawer

---

src/views/Flow/components/form/MQTTBrokerForm.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeMqttConfig.vue

https://emqx.atlassian.net/browse/ED-996

fix(bridge): add mqtt topic validation to local topic

---

src/assets/theme/editor-dark.json
src/components/Oneof.vue

https://emqx.atlassian.net/browse/ED-957
https://emqx.atlassian.net/browse/ED-984

fix(bridge): change monaco editor selection background color

---

src/views/Flow/components/form/MQTTBrokerForm.vue
src/views/Flow/components/form/source/MessageForm.vue

https://emqx.atlassian.net/browse/ED-996

fix(flow): fix can not validate the topic in message node

---

src/views/RuleEngine/components/RePubForm.vue

https://emqx.atlassian.net/browse/ED-1001

fix(rule): set boolean value to string

---

src/views/RuleEngine/components/RePubForm.vue

https://emqx.atlassian.net/browse/ED-1002

fix(rule): clear pub props conf after disable pub props

---

src/views/Clients/Clients.vue

https://emqx.atlassian.net/browse/ED-518

fix(clients): set width to time comparison select

---

src/views/Base/NavHeader.vue
src/views/Config/Monitoring/AlarmSettings.vue

after update alarm conf
https://emqx.atlassian.net/browse/ED-765

fix(alarm): alarm list is not updated

---

src/views/Config/Monitoring/MonitoringIntegration.vue

https://emqx.atlassian.net/browse/ED-761

fix(conf): update raw data for comparison after submitting

---

src/i18n/Clients.js
src/i18n/Gateway.js
src/views/Gateway/components/coapBasic.vue

https://emqx.atlassian.net/browse/ED-820
https://emqx.atlassian.net/browse/ED-655

fix(clients): update translation for nl rap and rh

---

src/components/CustomInputNumber.vue
src/components/Oneof.vue
src/components/SchemaForm.tsx
src/views/Auth/components/AuthzSettingDrawer.vue
src/views/Auth/components/DatabaseConfig.vue
src/views/Auth/components/HttpConfig.vue
src/views/Gateway/components/mqttsnBasic.vue
src/views/Gateway/components/stompBasic.vue
src/views/General/FlappingDetect.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeHttpConfig.vue
src/views/Webhook/components/WebhookForm.vue

https://emqx.atlassian.net/browse/ED-743

fix(auth): min value limit to database ID of redis

---

src/views/Dashboard/components/PolylineChart.vue

https://emqx.atlassian.net/browse/ED-993

fix(overview): x-axis label sometimes displays incompletely

---

src/i18n/RuleEngine.js
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue

https://emqx.atlassian.net/browse/ED-870

fix(bridge): optimized the error msg of `topic_mapping`

---

src/components/SchemaForm.tsx
src/hooks/useConfFooterStyle.ts
src/store/index.ts
src/style/schemaForm.scss
src/views/Config/BasicConfig/Cluster.vue
src/views/Config/BasicConfig/Limiter.vue
src/views/Config/BasicConfig/Log.vue
src/views/Config/BasicConfig/Mqtt.vue
src/views/Config/BasicConfig/Retainer.vue
src/views/Config/BasicConfig/Session.vue
src/views/Config/BasicConfig/SystemTopics.vue
src/views/Config/Monitoring/AlarmSettings.vue
src/views/Config/Monitoring/MonitoringIntegration.vue
src/views/General/FlappingDetect.vue

https://emqx.atlassian.net/browse/ED-941

fix(conf): handle footer when conf page is short

---

src/views/General/Users.vue

https://emqx.atlassian.net/browse/ED-1011

fix(user): viewer need to be able to change their passwords

---

src/hooks/SSO/useRole.ts
src/i18n/General.js
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/types/enum.ts
src/types/schemas/apiKeys.schemas.ts
src/types/schemas/authentication.schemas.ts
src/types/schemas/authorization.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/fileTransfer.schemas.ts
src/types/schemas/gatewayAuthentication.schemas.ts
src/types/schemas/gatewayListeners.schemas.ts
src/types/schemas/gateways.schemas.ts
src/types/systemModule.d.ts
src/views/General/APIKey.vue
src/views/General/Users.vue
src/views/General/components/APIKeyDialog.vue

https://emqx.atlassian.net/browse/ED-1016

feat(api_key): add role

---

src/hooks/useFormRules.ts
src/i18n/Base.js
src/i18n/General.js
src/views/Diagnose/LogTrace/LogTrace.vue
src/views/General/components/APIKeyDialog.vue

https://emqx.atlassian.net/browse/ED-1023

fix(api key & log trace): rule for name

---

src/hooks/Webhook/useWebhookItem.ts
src/hooks/Webhook/useWebhookList.ts
src/hooks/Webhook/useWebhookUtils.ts
src/router/index.ts
src/types/enum.ts
src/types/webhook.d.ts
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/Webhook/Webhook.vue
src/views/Webhook/WebhookDetail.vue

https://emqx.atlassian.net/browse/ED-1021

fix(webhook): unified the detail page with other places

---

src/components/Oneof.vue
src/hooks/Exhook/useHandleExhookItem.ts
src/views/Exhook/ExhookCreate.vue
src/views/Exhook/ExhookDetail.vue
src/views/Exhook/components/ExhookForm.vue

https://emqx.atlassian.net/browse/ED-1024

fix(exhook): correct rule of form

---

src/views/Flow/components/FlowEditor.vue

https://emqx.atlassian.net/browse/ED-1020

style(flow): del icon of flow node

---

src/types/enum.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue

https://emqx.atlassian.net/browse/ED-1026

fix(bridge): adapt new type for kafka producer

---

src/i18n/RuleEngine.js
src/views/RuleEngine/components/RePubForm.vue

https://emqx.atlassian.net/browse/ED-1028

style(rule): remove user props temporarily

---

src/views/RuleEngine/components/SQLTest.vue

https://emqx.atlassian.net/browse/ED-1030

fix(rule): confusing data in the result table

---

src/components/TLSConfig/TLSEnableConfig.vue
src/i18n/RuleEngine.js

https://emqx.atlassian.net/browse/ED-1033

fix(kafka): desc for SNI in bridge kafka

---

src/hooks/Rule/bridge/useBridgeFormCreator.ts
src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Schema/useItemLabelAndDesc.ts
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue

https://emqx.atlassian.net/browse/ED-1038

Hide `local_topic`

---

src/hooks/useFormRules.ts

https://emqx.atlassian.net/browse/ED-1041

fix(bridge): do not check topic when topic is not value

---

src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/hooks/Schema/useItemLabelAndDesc.ts
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json
src/style/schemaForm.scss
src/views/RuleEngine/Bridge/Components/ConnectorForm.vue
src/views/RuleEngine/Bridge/Components/UsingSchemaBridgeConfig.vue

feat(connector): support azure and add label for desc

---

src/i18n/General.js
src/i18n/RuleEngine.js
src/i18n/components.js
src/router/index.ts
src/views/Base/LeftBar.vue
src/views/General/Backup.vue

https://emqx.atlassian.net/browse/ED-1050

feat(backup): add backup static page

---

src/components/SchemaForm.tsx
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeInfluxdbConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConfig.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgePulsarConfig.vue
src/views/RuleEngine/Bridge/Components/UsingSchemaBridgeConfig.vue

https://emqx.atlassian.net/browse/ED-1044

fix(schema): mistake that occurred during code synchronization

---

package.json
src/common/tools.ts
src/components/SchemaForm.tsx
src/hooks/Rule/bridge/useDeleteBridge.ts
src/views/RuleEngine/Bridge/Components/DeleteBridgeSecondConfirm.vue

https://emqx.atlassian.net/browse/ED-1051

fix(bridge): show associated rule correctly

---

src/i18n/Gateway.js
src/views/Gateway/GatewayCreate.vue
src/views/Gateway/components/jt808Basic.vue

https://emqx.atlassian.net/browse/ED-1048

feat(gateway): adapt the jt808 gateway

---

src/common/constants.ts
src/components/ListenerDrawer/ListenerDrawer.vue
src/hooks/Config/useListenerUtils.ts
src/hooks/Gateway/useHandleGatewayData.ts
src/i18n/Gateway.js
src/types/enum.ts
src/views/Gateway/GatewayCreate.vue
src/views/Gateway/components/basic.vue
src/views/Gateway/components/ocppBasic.vue

https://emqx.atlassian.net/browse/ED-1047

feat(gateway): add ocpp gateway

---

src/common/docLinks.ts
src/views/Base/NavHeader.vue

https://emqx.atlassian.net/browse/ED-1056

feat(navHeader): add contact us button

---

src/components/Metrics/OverviewMetrics.vue
src/components/Metrics/TypeMetrics.vue
src/hooks/useMetrics.ts
src/i18n/Auth.js
src/i18n/Base.js
src/i18n/RuleEngine.js
src/views/Auth/AuthnDetails.vue
src/views/Auth/AuthzDetails.vue
src/views/Auth/components/AuthItemOverview.vue
src/views/RuleEngine/Bridge/Components/BridgeItemOverview.vue

https://emqx.atlassian.net/browse/ED-1057

refactor(authn): refactor authn overview metrics

---

src/hooks/useMetrics.ts
src/i18n/RuleEngine.js

https://emqx.atlassian.net/browse/ED-1018

refactor(bridge): update the bridge stats page

---

src/common/docLinks.ts
src/views/Settings/Help.vue

https://emqx.atlassian.net/browse/ED-1058

fix(docs): update mqtt v5 link

---

src/views/General/Users.vue

https://emqx.atlassian.net/browse/ED-1059

fix(users): reversed logic to judge show del button

---

src/components/Oneof.vue
src/hooks/Schema/useSchemaForm.ts
src/types/schemas/authorization.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/gateways.schemas.ts

https://emqx.atlassian.net/browse/ED-1062
https://emqx.atlassian.net/browse/ED-1059
when type is `number`, can not set the init value to 0, because for some fields (like 最大消息保留数), the `disabled value` is 0.....

fix(one of): set to undefined when enabled type is number

---

src/hooks/Flow/useGenerateFlowDataUtils.ts
src/hooks/Flow/useReuseBridgeInFlow.ts
src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/hooks/Rule/topology/useUtilsForTopology.ts
src/hooks/Rule/useDataHandler.ts
src/hooks/Webhook/useWebhookUtils.ts
src/views/RuleEngine/Bridge/BridgeCreate.vue
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/DataBridge.vue
src/views/RuleEngine/Connector/ConnectorCreate.vue
src/views/RuleEngine/Connector/ConnectorDetail.vue
src/views/RuleEngine/Connector/components/useConnectorFormComponent.ts

move some code to make it more reasonable

refactor(connector): handle general type in connector

---

src/components/Metrics/OverviewMetrics.vue
src/hooks/useMetrics.ts
src/i18n/RuleEngine.js
src/views/Flow/components/metrics/NodeMetrics.vue
src/views/RuleEngine/Bridge/Components/BridgeItemOverview.vue
src/views/RuleEngine/Rule/components/RuleItemOverview.vue

https://emqx.atlassian.net/browse/ED-1018

refactor(rule): update the rule stats page

---

src/components/Metrics/OverviewMetrics.vue
src/views/Flow/components/metrics/NodeMetrics.vue

https://emqx.atlassian.net/browse/ED-1018

refactor(flow): update the flow action nodes stats page

---

src/i18n/Gateway.js
src/views/Gateway/components/basic.vue
src/views/Gateway/components/jt808Basic.vue

https://emqx.atlassian.net/browse/ED-1048

feat(gateway): update jt808 gateway

---

src/common/tools.ts
src/views/RuleEngine/Connector/ConnectorCreate.vue
src/views/RuleEngine/Connector/components/ConnectorCreateDrawer.vue

scroll to top after step change

style(connector): width of connector drawer

---

src/i18n/MonitoringIntegration.js
src/types/dashboard.d.ts
src/views/Config/Monitoring/MonitoringIntegration.vue

https://emqx.atlassian.net/browse/ED-1065

refactor(monitoring): adapted the new prometheus API

---

package.json
src/api/ruleengine.ts
src/api/systemModule.ts
src/i18n/General.js
src/views/Base/NavHeader.vue
src/views/Gateway/components/jt808Basic.vue
src/views/General/Backup.vue
yarn.lock

https://emqx.atlassian.net/browse/ED-1050

feat(backup): add backup API

---

src/hooks/Flow/useFlowNode.ts
src/hooks/Rule/connector/useComponentsHandlers.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeKafkaConsumerConfig.vue

fix(action): handle missing label in kafka consumer

---

src/views/Gateway/components/coapBasic.vue
src/views/Gateway/components/exprotoBasic.vue
src/views/Gateway/components/lwm2mBasic.vue
src/views/Gateway/components/mqttsnBasic.vue
src/views/Gateway/components/ocppBasic.vue
src/views/Gateway/components/stompBasic.vue

https://emqx.atlassian.net/browse/ED-1072

fix(gateway): update the layout and values

---

src/api/ruleengine.ts
src/hooks/Flow/useFlowNode.ts
src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/hooks/Schema/useItemLabelAndDesc.ts
src/i18n/Flow.js
src/i18n/RuleEngine.js
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json
src/views/RuleEngine/Connector/components/ConnectorSchemaForm.vue
src/views/RuleEngine/components/RuleForm.vue
src/views/Webhook/components/WebhookForm.vue

https://emqx.atlassian.net/browse/ED-1071

refactor(action): add desc to fields in http and adjust some fields position

---

src/i18n/Dashboard.js
src/views/General/License.vue
src/views/General/components/LicenseResetDialog.vue

https://emqx.atlassian.net/browse/ED-1070

feat(license): support reset license to default

---

src/api/action.ts
src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useDeleteBridge.ts
src/hooks/Rule/connector/useComponentsHandlers.ts
src/hooks/Rule/connector/useHandleConnectorItem.ts
src/i18n/RuleEngine.js
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/DataBridge.vue
src/views/RuleEngine/Connector/Connector.vue

https://emqx.atlassian.net/browse/ED-1087
https://emqx.atlassian.net/browse/ED-1094
https://emqx.atlassian.net/browse/ED-1085

fix(action): handle delete action

---

src/api/systemModule.ts
src/hooks/Schema/useItemLabelAndDesc.ts
src/views/General/Backup.vue

https://emqx.atlassian.net/browse/ED-1082
https://emqx.atlassian.net/browse/ED-1095

fix(backup): pass node when downloading filr

---

src/views/Config/FileTransfer.vue

omit s3 when enabling local
omit local when enabling s3
https://emqx.atlassian.net/browse/ED-1098

fix(file transfer): omit unnecessary data when submitting

---

src/views/Auth/AuthnDetails.vue

convert data in old format to data in new format
https://emqx.atlassian.net/browse/ED-1102

fix(authn): handling data compatible

---

src/views/Auth/components/AuthzManager.vue
src/views/General/Users.vue

https://emqx.atlassian.net/browse/ED-1101
https://emqx.atlassian.net/browse/ED-1069

fix(authz): fix translation issue in perms list

---

src/common/constants.ts
src/i18n/Gateway.js
src/views/Gateway/GatewayCreate.vue
src/views/Gateway/components/basic.vue
src/views/Gateway/components/exprotoBasic.vue
src/views/Gateway/components/gbt32960Basic.vue
src/views/Gateway/components/jt808Basic.vue
src/views/Gateway/components/ocppBasic.vue
src/views/General/License.vue

https://emqx.atlassian.net/browse/ED-1079
https://emqx.atlassian.net/browse/ED-1092
https://emqx.atlassian.net/browse/ED-1078
https://emqx.atlassian.net/browse/ED-1093

Fix gateway bugs

---

scripts/checkAuditDict.js
src/views/General/AuditLog.vue
src/views/General/resource_dict.json

rename some duplicated label
https://emqx.atlassian.net/browse/ED-1108

fix(audit): add prefix for duplicated label

---

src/i18n/Auth.js

https://emqx.atlassian.net/browse/ED-1103

fix(auth): fix wrong metrics desc

---

src/views/Gateway/GatewayCreate.vue

https://emqx.atlassian.net/browse/ED-1093

fix(gateway): fix the tcp or ws default value for listener accptors

---

src/views/Subscriptions/Subscriptions.vue

https://emqx.atlassian.net/browse/ED-1074

fix(subs): fix topic translation issue

---

src/views/Base/LeftBar.vue
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/components/TableItemDropDown.vue

https://emqx.atlassian.net/browse/ED-1110
https://emqx.atlassian.net/browse/ED-1039

fix(left bar): add fixed height for long menu

---

src/hooks/Rule/connector/useComponentsHandlers.ts
src/i18n/RuleEngine.js

https://emqx.atlassian.net/browse/ED-1112

fix(connector): should disable `name` when editing

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/views/General/resource_dict.json

https://emqx.atlassian.net/browse/ED-1099

fix(action): order of fields in mysql form

---

src/i18n/Dashboard.js
src/types/dashboard.d.ts
src/views/General/License.vue

https://emqx.atlassian.net/browse/ED-1068

fix(license): fix the rule message for usage watermark

---

src/i18n/MonitoringIntegration.js
src/types/dashboard.d.ts
src/views/Config/Monitoring/MonitoringIntegration.vue

https://emqx.atlassian.net/browse/ED-1105

refactor(monitor): adapt the new config for opentelemetry

---

src/i18n/MonitoringIntegration.js
src/types/dashboard.d.ts
src/types/schemas/bridges.schemas.ts
src/types/schemas/monitor.schemas.ts
src/views/Config/Monitoring/MonitoringIntegration.vue

https://emqx.atlassian.net/browse/ED-1105

refactor(monitor): add export interval for opentelemetry config

---

src/i18n/General.js
src/types/schemas/actions.schemas.ts
src/types/schemas/bridges.schemas.ts
src/types/schemas/connectors.schemas.ts
src/types/schemas/gateways.schemas.ts
src/types/schemas/monitor.schemas.ts
src/views/General/AuditLog.vue
src/views/General/resource_dict.json

https://emqx.atlassian.net/browse/ED-1106
https://emqx.atlassian.net/browse/ED-1107

fix(audit): check time range before searching

---

src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-1096

fix(connector): rename `azure event hub` to `...hubs` in desc

---

src/views/Auth/AuthnDetails.vue
src/views/Auth/AuthzDetails.vue
src/views/Flow/components/form/MQTTBrokerForm.vue
src/views/RuleEngine/components/RePubForm.vue

https://emqx.atlassian.net/browse/ED-1064
https://emqx.atlassian.net/browse/ED-1089

fix(rule): disabled switch when readonly

---

src/components/SchemaForm.tsx
src/hooks/Rule/action/useHandleActionItem.ts
src/hooks/Rule/bridge/useDeleteBridge.ts
src/i18n/RuleEngine.js
src/style/schemaForm.scss
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/Components/DeleteBridgeSecondConfirm.vue
src/views/RuleEngine/Bridge/DataBridge.vue

https://emqx.atlassian.net/browse/ED-1113

fix(schema form): add scroll bar to tooltip content

---

src/hooks/Flow/useFlowNode.ts
src/hooks/Flow/useNodeDrawer.ts
src/i18n/RuleEngine.js

forgot English...
https://emqx.atlassian.net/browse/ED-1077

fix(rule): rename function to data processing

---

src/schemaText/symbol-label-en.json
src/schemaText/symbol-label-zh.json

in http action form
https://emqx.atlassian.net/browse/ED-1116

fix(action): consistent with webhook option label

---

src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/views/Config/FileTransfer.vue

https://emqx.atlassian.net/browse/ED-1113
https://emqx.atlassian.net/browse/ED-1118

refactor(file): handle `versions` and `ciphers` in TLS

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Webhook/useWebhookForm.ts
src/i18n/RuleEngine.js
src/i18n/components.js
src/views/RuleEngine/Bridge/Components/BridgeItemOverview.vue
src/views/RuleEngine/Bridge/DataBridge.vue

https://emqx.atlassian.net/browse/ED-1119

refactor(action): prompt when action list is empty

---

src/i18n/RuleEngine.js
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/DataBridge.vue
src/views/RuleEngine/Connector/Connector.vue
src/views/RuleEngine/Connector/ConnectorDetail.vue
src/views/RuleEngine/components/TargetItemStatus.vue

https://emqx.atlassian.net/browse/ED-1123

refactor(action): change the status text

---

src/hooks/useMetrics.ts

https://emqx.atlassian.net/browse/EMQX-11494
https://emqx.atlassian.net/browse/ED-1124

fix(rule): only show the actions failed as total

---

src/hooks/Flow/useGenerateFlowDataUtils.ts

https://emqx.atlassian.net/browse/ED-1120

fix(flow): logic to parse function expressions

---

src/style/normalize.scss
src/views/Config/Monitoring/MonitoringIntegration.vue

https://emqx.atlassian.net/browse/ED-1125

fix(gateway): styling issue in dark mode

---

src/hooks/Flow/useFlowNode.ts
src/views/Gateway/components/jt808Basic.vue

please have a confirmation
https://github.com/emqx/emqx/pull/12190
https://emqx.atlassian.net/browse/ED-1122

refactor(gateway): form structure changes in JT808

---

src/components/Metrics/OverviewMetrics.vue
src/views/Exhook/ExhookDetail.vue
src/views/Exhook/components/ExhookItemOverview.vue
src/views/RuleEngine/Rule/components/RuleItemOverview.vue

https://emqx.atlassian.net/browse/ED-1100

fix(exhook): fix can not show metrics when data loaded

---

src/style/schemaForm.scss
src/views/Config/Monitoring/MonitoringIntegration.vue

https://emqx.atlassian.net/browse/ED-1130

fix(monitoring): show TLS file path if there is a value

---

src/views/RuleEngine/components/TargetItemStatus.vue

https://emqx.atlassian.net/browse/ED-1131

fix(rule): some error status texts on action

---

src/hooks/Config/useListenerDialog.ts
src/i18n/BasicConfig.js
src/i18n/Gateway.js

https://emqx.atlassian.net/browse/ED-1136
https://github.com/emqx/emqx/pull/12201

fix(listener): update confirm tips

---

src/i18n/Gateway.js

style(gateway): optimize some label

---

src/common/constants.ts
src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Rule/connector/useComponentsHandlers.ts
src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/hooks/Rule/connector/useTestConnector.ts
src/hooks/Rule/useDataHandler.ts
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json
src/schemaText/symbol-label-en.json
src/schemaText/symbol-label-zh.json
src/views/RuleEngine/Bridge/Components/UsingSchemaBridgeConfig.vue

fix(connector): handle account json before submitting

---

src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeResourceOpt.vue
src/views/Webhook/components/WebhookForm.vue

https://emqx.atlassian.net/browse/ED-1139

fix(webhook): `start_timeout` is in connector

---

src/common/constants.ts
src/hooks/Rule/topology/useRule.ts
src/hooks/useRuleFunc.ts
src/style/normalize.scss
src/views/Flow/components/NodeDrawer.vue
src/views/Flow/components/form/processing/FunctionBlock.vue
src/views/Flow/components/form/processing/FunctionForm.vue

only show the usable fields in field input
part of https://emqx.atlassian.net/browse/ED-956

fix(flow): change function selection to cascader

---

src/views/Config/Monitoring/MonitoringIntegration.vue

for compare
https://emqx.atlassian.net/browse/ED-1129

fix(monitoring): update raw data after submitting

---

src/i18n/Gateway.js
src/views/Gateway/GatewayCreate.vue
src/views/Gateway/components/auth.vue

https://emqx.atlassian.net/browse/ED-1143
https://emqx.atlassian.net/browse/ED-1140

feat(gateway): add tips for jt808 auth

---

src/i18n/General.js
src/views/General/AuditLog.vue

common and for HTTP/API Key
https://emqx.atlassian.net/browse/ED-1135

refactor(audit): split search filters into two blocks

---

src/views/AdvancedMQTT/AutoSub.vue
src/views/AdvancedMQTT/DelayedPub.vue
src/views/AdvancedMQTT/Rewrite.vue
src/views/Config/BasicConfig/Retainer.vue
src/views/General/FlappingDetect.vue

https://emqx.atlassian.net/browse/ED-1157

fix(config): fix keyup perms check issue on config page

---

src/hooks/Rule/action/useHandleActionItem.ts
src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/views/RuleEngine/Bridge/BridgeCreate.vue
src/views/RuleEngine/Connector/ConnectorCreate.vue
src/views/RuleEngine/components/RuleForm.vue
src/views/RuleEngine/components/RuleOutputs.vue
src/views/RuleEngine/components/RuleOutputsDrawer.vue

https://emqx.atlassian.net/browse/ED-1086

feat(connector): create rule quickly after connector creation

---

package.json
public/static/templates/EMQX_InfluxDB_Template.csv
src/components/BatchSettings.vue
src/i18n/Base.js
src/types/enum.ts
src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbFieldsEditor.vue
src/views/RuleEngine/components/FromSelect.vue
yarn.lock

https://emqx.atlassian.net/browse/ED-1160

feat(connector): influxdb support upload fields template

---

public/static/templates/EMQX_TDengine_Template.csv
src/components/AdvancedSettingContainer.vue
src/components/BatchSettings.vue
src/components/OneofRefs.vue
src/components/SchemaForm.tsx
src/style/schemaForm.scss
src/types/enum.ts
src/views/Flow/components/NodeDrawer.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbFieldsEditor.vue
src/views/RuleEngine/Bridge/Components/UsingSchemaBridgeConfig.vue

https://emqx.atlassian.net/browse/ED-1160

feat(action): tdengine support the batch settings

---

src/hooks/useMetrics.ts
src/views/Auth/AuthnDetails.vue
src/views/Exhook/ExhookDetail.vue
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Rule/RuleDetail.vue
src/views/RuleEngine/Source/SourceDetail.vue
src/views/Webhook/WebhookDetail.vue

fix(action): fix warning in console

---

src/views/Webhook/Webhook.vue

https://emqx.atlassian.net/browse/ED-1166

fix(webhook): fixed url display

---

src/i18n/Gateway.js

https://emqx.atlassian.net/browse/ED-1158

fix(gateway): update en translation for msgQueueLen

---

public/static/templates/EMQX_IoTDB_Template.csv
src/components/BatchSettings.vue
src/components/ObjectArrayEditor.vue
src/components/SchemaForm.tsx

https://emqx.atlassian.net/browse/ED-1160

feat(rules): iotdb support batch settings

---

src/components/SchemaForm.tsx

https://emqx.atlassian.net/browse/ED-1178       the second
https://emqx.atlassian.net/browse/ED-1167

fix(schema): logic to judge is complex one of

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/useDataHandler.ts
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json
src/types/schemas/actions.schemas.ts
src/types/schemas/connectors.schemas.ts
src/types/schemas/gateways.schemas.ts
src/views/RuleEngine/Connector/components/useConnectorFormComponent.ts

https://emqx.atlassian.net/browse/ED-1173
https://emqx.atlassian.net/browse/ED-1178 the first

test(schemas): update schemas

---

src/hooks/Flow/useFlowNode.ts

Some optimization is needed here..
https://emqx.atlassian.net/browse/ED-1180

fix(flow): add SysKeeperForwarder to sink type

---

src/views/Flow/components/NodeDrawer.vue

https://emqx.atlassian.net/browse/ED-1175

fix(flow): refresh the component after changing the selection

---

src/components/ArrayEditor.vue
src/components/ListenerDrawer/ListenerDrawer.vue
src/hooks/Config/useListenerUtils.ts
src/i18n/Gateway.js
src/views/RuleEngine/Source/SourceDetail.vue

https://emqx.atlassian.net/browse/ED-1170
https://emqx.atlassian.net/browse/ED-1176

feat(listener): add cipher suite support in tls options

---

src/hooks/Rule/bridge/useDeleteBridge.ts
src/hooks/Rule/connector/useHandleConnectorItem.ts
src/views/RuleEngine/Connector/Connector.vue
src/views/RuleEngine/Connector/ConnectorDetail.vue
src/views/RuleEngine/Source/SourceDetail.vue

https://emqx.atlassian.net/browse/ED-1168

fix(connector): unified delete operation

---

src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeInfluxdbConfig.vue

https://emqx.atlassian.net/browse/ED-1185

fix(action): fix `precision` opt error in influxDB

---

src/components/AdvancedSettingsBtn.vue
src/components/KeyAndValueEditor.vue
src/components/Monaco.vue
src/hooks/Rule/bridge/useDeleteBridge.ts
src/hooks/Rule/connector/useHandleConnectorItem.ts
src/hooks/Webhook/useWebhookForm.ts
src/hooks/Webhook/useWebhookUtils.ts
src/i18n/RuleEngine.js
src/style/normalize.scss
src/style/rule.scss
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/Components/ConnectorSelect.vue
src/views/RuleEngine/Bridge/Components/UsingSchemaBridgeConfig.vue
src/views/RuleEngine/Bridge/DataBridge.vue
src/views/RuleEngine/Connector/Connector.vue
src/views/RuleEngine/Connector/ConnectorDetail.vue
src/views/RuleEngine/Connector/components/ConnectorSchemaForm.vue
src/views/RuleEngine/Rule/Rule.vue
src/views/RuleEngine/Rule/RuleDetail.vue
src/views/RuleEngine/Rule/components/ActionSelect.vue
src/views/RuleEngine/components/DeleteWebhookAssociatedTip.vue
src/views/RuleEngine/components/RuleForm.vue
src/views/RuleEngine/components/RuleInputs.vue
src/views/RuleEngine/components/RuleOutputs.vue
src/views/Webhook/WebhookDetail.vue
src/views/Webhook/components/WebhookForm.vue

https://emqx.atlassian.net/browse/ED-1165

Improve Webhook

---

src/common/constants.ts
src/types/enum.ts

https://emqx.atlassian.net/browse/ED-1186

fix(gateway): hide ws for mqtt sn

---

src/api/extension.ts
src/components/ArrayEditor.vue
src/i18n/Auth.js
src/i18n/Base.js
src/i18n/BasicConfig.js
src/i18n/General.js
src/types/auth.d.ts
src/views/Auth/components/AuthzSettingDrawer.vue
src/views/General/BannedClient.vue
src/views/Retained/Retained.vue

https://emqx.atlassian.net/browse/ED-1187
https://emqx.atlassian.net/browse/ED-1154
https://emqx.atlassian.net/browse/ED-1153

fix(listener): modify listener update tip messages

---

src/components/OneofRefs.vue
src/hooks/Schema/useSchemaForm.ts

part of https://emqx.atlassian.net/browse/ED-1188

refactor(schema): set default value for one of refs

---

src/api/extension.ts
src/views/Retained/Retained.vue

https://emqx.atlassian.net/browse/ED-1153

fix(retained): fix oper button disable issue

---

src/common/constants.ts
src/hooks/Rule/bridge/useCheckBeforeSaveAsCopy.ts
src/types/enum.ts
src/types/schemas/authorization.schemas.ts
src/types/schemas/gateways.schemas.ts
src/types/schemas/mqtt.schemas.ts
src/types/schemas/retainer.schemas.ts
src/views/Flow/components/NodeDrawer.vue
src/views/Flow/components/form/MQTTBrokerForm.vue

https://emqx.atlassian.net/browse/ED-1181
https://emqx.atlassian.net/browse/ED-1189
https://emqx.atlassian.net/browse/ED-1184

fix(flow): rename label Remote Broker to Ingress/Egress

---

src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/views/RuleEngine/Connector/ConnectorCreate.vue

https://emqx.atlassian.net/browse/ED-1198

fix(connector): missing type in guide bar when selecting syskeeper proxy

---

src/views/Config/FileTransfer.vue

https://emqx.atlassian.net/browse/ED-1159

fix(file transfer): get basic config before changing type

---

src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json

https://emqx.atlassian.net/browse/ED-1197

fix(action): add desc to `data_type` in IoTDB

---

src/components/Monaco.vue
src/views/Diagnose/LogTrace/LogTraceDetail.vue

https://emqx.atlassian.net/browse/ED-1148

fix(log trace): cannot display empty content

---

src/components/TimeInputWithUnitSelect.vue

https://emqx.atlassian.net/browse/ED-1149

refactor(time input): support input number

---

src/views/RuleEngine/Bridge/DataBridge.vue
src/views/RuleEngine/Connector/Connector.vue
src/views/RuleEngine/Source/Source.vue
src/views/RuleEngine/components/TableItemDropDown.vue

https://emqx.atlassian.net/browse/ED-1183

fix(connector): add button to list page for create rule with connector

---

src/hooks/Rule/bridge/useCheckBeforeSaveAsCopy.ts
src/hooks/Rule/useDataHandler.ts

https://emqx.atlassian.net/browse/ED-1184
https://emqx.atlassian.net/browse/ED-1189

fix(connector): password processing when copying

---

src/components/BatchSettings.vue
src/i18n/General.js
src/i18n/components.js

https://emqx.atlassian.net/browse/ED-1191

fix(influxdb): refactor data processing and remove unused translations

---

src/views/Flow/components/NodeDrawer.vue

https://emqx.atlassian.net/browse/ED-1175

fix(flow): logic to detect whether it is editing

---

src/components/BatchSettings.vue
src/i18n/General.js

https://emqx.atlassian.net/browse/ED-1190

fix(components): add file upload validation message for batch settings

---

src/common/constants.ts
src/components/BatchSettings.vue
src/i18n/General.js

https://emqx.atlassian.net/browse/ED-1193
https://emqx.atlassian.net/browse/ED-1202

fix(components): add batch upload csv row limit

---

src/i18n/BasicConfig.js

https://emqx.atlassian.net/browse/ED-1201

fix(listener): modify listener update tips

---

public/static/templates/EMQX_InfluxDB_Template.csv
public/static/templates/EMQX_IoTDB_Template.csv
public/static/templates/EMQX_TDengine_Template.csv
src/components/BatchSettings.vue
src/i18n/General.js

https://emqx.atlassian.net/browse/ED-1195

refactor(components): update the batch settings csv template

---

src/components/OneofRefs.vue
src/components/SchemaFormItem.tsx
src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/connector/useComponentsHandlers.ts
src/views/Flow/components/form/processing/FunctionBlock.vue

https://emqx.atlassian.net/browse/ED-1207
https://emqx.atlassian.net/browse/ED-1204

fix(flow): handle args after selecting func

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json
src/schemaText/symbol-label-zh.json
src/views/RuleEngine/Bridge/BridgeDetail.vue

https://emqx.atlassian.net/browse/ED-1205

fix(connector): add missing labels in elasticsearch

---

src/hooks/Webhook/useWebhookUtils.ts
src/i18n/Base.js
src/i18n/RuleEngine.js
src/views/Flow/components/FlowSelectDialog.vue
src/views/Flow/components/FlowView.vue
src/views/Flow/components/NodeDrawer.vue
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/DataBridge.vue
src/views/RuleEngine/Connector/Connector.vue
src/views/RuleEngine/Connector/ConnectorDetail.vue
src/views/RuleEngine/Rule/Rule.vue
src/views/RuleEngine/Rule/RuleDetail.vue
src/views/RuleEngine/components/OperateWebhookAssociatedPopover.vue
src/views/RuleEngine/components/RuleForm.vue

https://emqx.atlassian.net/browse/ED-1203

fix(flow): limit operation webhook

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/hooks/Config/useListenerDialog.ts

https://emqx.atlassian.net/browse/ED-1200

fix(listener): do not delete empty value when updating

---

src/components/Metrics/OverviewMetrics.vue
src/hooks/useMetrics.ts
src/types/common.d.ts
src/views/RuleEngine/Rule/components/RuleItemOverview.vue

https://emqx.atlassian.net/browse/ED-1210

refactor(rule): update the rule metrics page

---

src/hooks/Rule/connector/useComponentsHandlers.ts

https://emqx.atlassian.net/browse/ED-1216

fix(connector): set the type of time-related config items to `duration`

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts

in IoTDB
https://emqx.atlassian.net/browse/ED-1199

fix(connector): the position of `iotdb_version`

---

src/types/schemas/actions.schemas.ts
src/types/schemas/authentication.schemas.ts
src/types/schemas/bridges.schemas.ts
src/types/schemas/cluster.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/connectors.schemas.ts
src/types/schemas/gatewayAuthentication.schemas.ts
src/types/schemas/gatewayListeners.schemas.ts
src/types/schemas/gateways.schemas.ts
src/types/schemas/sources.schemas.ts
src/views/General/resource_dict.json

https://emqx.atlassian.net/browse/ED-1214

fix(audit): update dict for `/cluster/:node/invite_async`

---

src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbFieldsEditor.vue

https://emqx.atlassian.net/browse/ED-1194

fix(influxdb): performance improve with pagination for table data

---

src/views/RuleEngine/components/SQLTest.vue

https://emqx.atlassian.net/browse/ED-1225

fix(rule): fix can not handle null value in rule test

---

src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/schemaText/bridge-text-en.json
src/schemaText/bridge-text-zh.json
src/views/General/resource_dict.json

adapt https://github.com/emqx/emqx/pull/12371
https://emqx.atlassian.net/browse/ED-1214

refactor(connector): adapt field change in Elasticsearch

---

src/views/RuleEngine/components/RuleOutputsDrawer.vue

https://emqx.atlassian.net/browse/ED-1226

fix(rule): fix the logic of submission when editing action

---

src/hooks/Rule/bridge/useComponentsHandlers.ts

https://emqx.atlassian.net/browse/ED-1224

fix(action): remove qos2 for ingress in mqtt source

---

src/hooks/Rule/bridge/useComponentsHandlers.ts

doc(action): add a comment when remove QoS2 in MQTT

---

src/common/docLinks.ts
src/components/BatchSettings.vue
src/i18n/Base.js

https://emqx.atlassian.net/browse/ED-1190

fix(doc): add batch settings documentation links

---

.github/workflows/build_emqx_for_test.yaml
src/components/Metrics/TypeMetrics.vue
src/types/schemas/actions.schemas.ts
src/types/schemas/monitor.schemas.ts
src/types/schemas/sources.schemas.ts

https://emqx.atlassian.net/browse/ED-1227

fix(integration): text color in dark mode

---

src/common/constants.ts
src/components/BatchSettings.vue
src/i18n/Base.js

https://emqx.atlassian.net/browse/ED-1194

fix(influxdb): update file size and max rows limit

---

src/hooks/useMetrics.ts
src/i18n/RuleEngine.js
src/views/RuleEngine/Rule/components/RuleItemOverview.vue

https://emqx.atlassian.net/browse/ED-1210

fix(rule): some missing changes

---

src/common/constants.ts
src/components/BatchSettings.vue
src/hooks/Auth/usePasswordHashAlgorithmData.ts
src/i18n/Base.js

https://emqx.atlassian.net/browse/ED-1194

fix(components): update batch upload CSV max rows

---

src/i18n/Dashboard.js
src/views/Dashboard/components/PolylineCards.vue
src/views/Dashboard/components/PolylineChart.vue

https://emqx.atlassian.net/browse/ED-1228

fix(overview): add unit for line chart tooltip

---

src/types/client.d.ts
src/views/Clients/ClientDetails.vue

https://emqx.atlassian.net/browse/ED-1230
Fixed some types error.

feat(client): support refresh the subs table data

---

src/App.vue
src/hooks/useGetInfoFromQuery.ts
src/hooks/useUpdateBaseInfo.ts

for ECP
https://emqx.atlassian.net/browse/ED-1237

feat(global): can get user info from route query

---

src/views/RuleEngine/components/SQLTest.vue

style(rule): optimize some style of json viewer

---

src/hooks/Auth/useBannedType.ts
src/i18n/Clients.js
src/types/enum.ts

https://emqx.atlassian.net/browse/ED-1238

feat(banned): add more banned object

---

.github/workflows/build_emqx_for_test.yaml
src/i18n/BasicConfig.js
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/types/schemas/authentication.schemas.ts
src/types/schemas/authorization.schemas.ts
src/types/schemas/banned.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/gateways.schemas.ts

https://emqx.atlassian.net/browse/ED-1248

refactor(log): add new config `throttling`

---

src/views/Flow/components/NodeDrawer.vue

https://emqx.atlassian.net/browse/ED-1250

fix(flow): logic to detect direction

---

src/hooks/Rule/useDataHandler.ts

https://emqx.atlassian.net/browse/ED-1251

fix(connector): check `secret_access_key` before save as copy

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/i18n/Base.js
src/i18n/Gateway.js
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json

https://emqx.atlassian.net/browse/ED-1245

refactor(listener): add advanced settings for configs

---

src/common/constants.ts
src/views/Flow/components/metrics/NodeMetrics.vue
src/views/RuleEngine/Connector/components/CreateRuleWithConnector.vue

https://emqx.atlassian.net/browse/ED-1252

fix(flow): should get source detail when node is input node

---

src/components/DetailHeader.vue
src/style/common.scss
src/style/normalize.scss
src/views/AdvancedMQTT/DelayedPub.vue
src/views/Base/Layout.vue
src/views/Base/NavHeader.vue
src/views/Config/BasicConfig/Log.vue
src/views/Dashboard/NodeDetail.vue
src/views/Dashboard/Nodes.vue
src/views/Diagnose/SlowSub.vue
src/views/Diagnose/WebSocket.vue
src/views/Flow/FlowHandler.vue
src/views/Flow/Index.vue
src/views/Gateway/Gateway.vue
src/views/General/FlappingDetect.vue
src/views/RuleEngine/Rule/Rule.vue
src/views/RuleEngine/Rule/components/RuleFilterForm.vue
src/views/Subscriptions/Subscriptions.vue

style(layout): move first title to header

---

src/views/Base/NavHeader.vue

Otherwise, the test CI for dashboard will fail.

style(header): change the title tag

---

src/common/constants.ts
src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/types/schemas/actions.schemas.ts
src/types/schemas/bridges.schemas.ts
src/types/schemas/connectors.schemas.ts

https://emqx.atlassian.net/browse/ED-1256

refactor(connector & action): DynamoDB

---

src/components/TimeInputWithUnitSelect.vue
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/views/Topics/Topics.vue

https://emqx.atlassian.net/browse/ED-1253

doc(log): update desc for `time_window`

---

src/common/constants.ts
src/components/ListenerDrawer/CustomConfigs.vue
src/components/ListenerDrawer/ListenerDrawer.vue
src/hooks/Config/useListenerDialog.ts
src/hooks/Config/useListenerUtils.ts
src/i18n/Gateway.js

https://emqx.atlassian.net/browse/ED-1245

feat(listener): support custom configs

---

src/views/Webhook/components/WebhookForm.vue

https://emqx.atlassian.net/browse/ED-1266

fix(webhook): label missing

---

src/common/constants.ts
src/hooks/Flow/useFlowNode.ts
src/hooks/Flow/useGenerateFlowDataUtils.ts
src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/i18n/RuleEngine.js
src/views/RuleEngine/Connector/components/CreateRuleWithConnector.vue
src/views/RuleEngine/Connector/components/DelConnectorTip.vue
src/views/RuleEngine/components/RuleForm.vue

https://emqx.atlassian.net/browse/ED-1267

fix(connector): wrong prompt content when deleting kafka consumer

---

src/views/General/components/BannedDialog.vue

https://emqx.atlassian.net/browse/ED-1265

fix(banned): change the trigger method in create form

---

src/api/ruleengine.ts
src/api/sources.ts
src/i18n/Clients.js
src/views/Clients/components/MessageListDialog.vue
src/views/RuleEngine/components/SQLTest.vue

https://emqx.atlassian.net/browse/ED-1268

fix(rule): error message when test fails

---

src/hooks/Rule/action/useHandleSourceItem.ts

https://emqx.atlassian.net/browse/EMQX-11948
https://emqx.atlassian.net/browse/EMQX-11946

fix(source): incorrect data to API when testing connection

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/schemaText/actionText/action-desc-en.json
src/schemaText/actionText/action-desc-zh.json
src/schemaText/actionText/action-label-en.json
src/schemaText/actionText/action-label-zh.json

https://emqx.atlassian.net/browse/ED-1269

fix(action): distinguish same `batch_sizes` in HStream

---

src/components/InputWithUnit.vue

https://emqx.atlassian.net/browse/ED-1270

fix(InputWithUnit): not displaying correctly when using uppercase units

---

src/views/Clients/ClientDetails.vue

https://emqx.atlassian.net/browse/ED-1274

fix(client): fix can not show messages in mqtt v3

---

src/i18n/Rule.js
src/types/schemas/clients.schemas.ts
src/types/schemas/configs.schemas.ts
src/views/Base/QuickPanel.vue

https://emqx.atlassian.net/browse/ED-1285
https://emqx.atlassian.net/browse/ED-1281

fix(quick panel): escape reg exp before search

---

src/components/SchemaForm.tsx
src/style/normalize.scss

https://emqx.atlassian.net/browse/ED-1289
https://emqx.atlassian.net/browse/ED-1290

fix(action): cannot create after uploading template in TDengine

---

src/hooks/Config/useListenerDialog.ts
src/hooks/Config/useListenerUtils.ts

https://emqx.atlassian.net/browse/ED-1286
https://emqx.atlassian.net/browse/ED-1288

fix(listener): update the current type custom config only

---

src/common/constants.ts
src/components/ListenerDrawer/ListenerDrawer.vue
src/i18n/Base.js

https://emqx.atlassian.net/browse/ED-1293
https://emqx.atlassian.net/browse/ED-1283
https://emqx.atlassian.net/browse/ED-1294

fix(listener): remove used configs

---

src/i18n/RuleEngine.js
src/views/General/resource_dict.json
src/views/RuleEngine/Schema/components/SchemaRegistryForm.vue

https://emqx.atlassian.net/browse/ED-1282

fix(audit log): update resource dict

---

src/components/ListenerDrawer/CustomConfigs.vue
src/components/ListenerDrawer/ListenerDrawer.vue
src/hooks/Config/useListenerDialog.ts
src/hooks/Config/useListenerUtils.ts

https://emqx.atlassian.net/browse/ED-1292

fix(listener): add validate for custom config when submit

---

src/hooks/Config/useListenerUtils.ts

https://emqx.atlassian.net/browse/ED-1298

fix(listener): fix can not config websocket subprotos

---

src/App.vue
src/common/tools.ts
src/hooks/useGetInfoFromQuery.ts
src/store/index.ts

https://emqx.atlassian.net/browse/ED-1237

feat(global): support set lang in query

---

src/components/InputWithUnit.vue

https://emqx.atlassian.net/browse/ED-1301

fix(InputWithUnit): logical error in judgement unit

---

.github/workflows/check_audit_dict.yaml
.github/workflows/project_test.yaml
package.json
scripts/checkAuditDict.js

test(ci): add ci for check audit dict

---

src/types/schemas/clients.schemas.ts
src/types/schemas/metrics.schemas.ts
src/views/Webhook/components/Trigger.vue

https://emqx.atlassian.net/browse/ED-1302

fix(webhook): topic list is incorrect when viewing webhook

---

package.json
src/views/RuleEngine/Schema/components/SchemaRegistryForm.vue
yarn.lock

https://emqx.atlassian.net/browse/ED-1303

fix(schema registry): issue with json schema validation

---

src/hooks/Config/useListenerDialog.ts
src/i18n/Clients.js

https://emqx.atlassian.net/browse/ED-1305

fix(banned): update the zh name

---

src/views/RuleEngine/Schema/components/JSONSchemaGeneratorDialog.vue

https://emqx.atlassian.net/browse/ED-1304

fix(schema): specify the version in the generated schema

---

src/views/RuleEngine/Schema/components/SchemaRegistryForm.vue

https://emqx.atlassian.net/browse/ED-1307

refactor(schema): default version of json schema changed to 06

---

src/i18n/Clients.js
src/types/schemas/clients.schemas.ts
src/types/schemas/sources.schemas.ts
src/types/schemas/topics.schemas.ts
src/views/Clients/components/MessageListDialog.vue

https://emqx.atlassian.net/browse/ED-1260
https://emqx.atlassian.net/browse/ED-1277

refactor(client): use `inserted_at` to compare instead of `publish_at`

---

src/components/Monaco.vue

https://emqx.atlassian.net/browse/ED-1309

fix(json schema): unnecessary warning in monaco editor

---

src/App.vue
src/api/sso.ts
src/common/tools.ts
src/hooks/useGetInfoFromQuery.ts
src/hooks/useUpdateBaseInfo.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/dashboard.schemas.ts
src/types/schemas/dashboardSingleSignOn.schemas.ts
src/types/typeAlias.ts

`c` is customer, I don't want it to be too obvious

feat(global): support get token from query

---

src/App.vue
src/common/tools.ts
src/hooks/SSO/useSSO.ts
src/hooks/SSO/useSSODetail.ts
src/i18n/General.js
src/store/index.ts
src/views/Base/Layout.vue
src/views/General/components/SSOForm/IframeForm.vue
src/views/General/components/SSOForm/LDAPForm.vue
src/views/General/components/SSOForm/SAMLForm.vue

feat(layout): support hide menu from query

---

src/common/tools.ts
src/components/InputWithPlaceholderSelect.vue
src/hooks/Flow/useGenerateFlowDataUtils.ts
src/hooks/Rule/rule/useRule.ts
src/hooks/Rule/useSQLAvailablePlaceholder.ts

https://github.com/emqx/emqx-dashboard5/assets/26165221/ddefc497-a07a-4e62-bc35-8a0cb75ab008

feat(component): init `InputWithPlaceholderSelect`

---

src/components/InputWithPlaceholderSelect.vue

I realised there was no need to write an autocomplete.🤦🏻‍♀️🤦🏻‍♀️🤦🏻‍♀️

refactor(component): refactor the `InputWithPlaceholderSelect`

---

src/hooks/SSO/useSSODetail.ts

https://emqx.atlassian.net/browse/ED-1323

fix(sso): the default value of `verify`

---

src/components/Monaco.vue
src/hooks/Rule/useProvidersForMonaco.ts
src/hooks/Rule/useSQLAvailablePlaceholder.ts

https://github.com/emqx/emqx-dashboard5/assets/26165221/88526f52-d21f-42e1-8bc5-a29736bda8e5

feat(monaco provider): support generate provider by sql

---

src/components/InputWithPlaceholderSelect.vue
src/components/Monaco.vue
src/components/SchemaForm.tsx
src/hooks/Flow/useFlowEditorDataHandler.ts
src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/useProvidersForMonaco.ts
src/hooks/Rule/useSQLAvailablePlaceholder.ts
src/style/normalize.scss
src/views/Flow/components/FlowEditor.vue
src/views/RuleEngine/components/RuleForm.vue

not done, still missing `KeyAndValueEditor`..

feat(action): support select placeholder in http & mqtt

---

src/views/General/Backup.vue

base url for cloud is `/dashboard/api/v5`, need to dynamically render the upload request url.

refactor(backup): use getAPIPath to render upload file request url

---

.github/workflows/build_enterprise_package.yaml
.github/workflows/build_oss_package.yaml
src/components/commonPagination.vue

chore(ci): update the version of nodejs

---

.github/workflows/build_enterprise_package.yaml
.github/workflows/build_oss_package.yaml
.github/workflows/check_package_version.yaml
.github/workflows/tag.yaml
scripts/checkPackageVersion.js

chore(ci): add ci for check version in package

---

src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json

https://emqx.atlassian.net/browse/ED-1324

fix(mqtt): update dispatch strategy descriptions for shared subscriptions

---

src/api/systemModule.ts
src/views/General/Backup.vue

https://emqx.atlassian.net/browse/ED-1325

feat(backup): change the default timeout for upload backup

---

src/api/systemModule.ts

https://emqx.atlassian.net/browse/ED-1325

fix(backup): add timeout config for restore

---

src/hooks/Clients/useClientDetail.ts
src/hooks/Clients/useClientFields.ts
src/i18n/Base.js
src/i18n/Clients.js
src/views/Clients/ClientDetails.vue
src/views/Clients/Clients.vue
src/views/Clients/components/ClientFieldSelect.vue
src/views/Clients/components/ClientInfoItem.vue

https://emqx.atlassian.net/browse/ED-1328

feat(client): support select column in list page

---

src/i18n/Clients.js
src/views/Clients/ClientDetails.vue

https://emqx.atlassian.net/browse/ED-1337

feat(client): add desc for mqueue and inflight

---

src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/views/Config/BasicConfig/Mqtt.vue

https://emqx.atlassian.net/browse/ED-1339

feat(mqtt): adapt new config `client_attrs_init`

---

src/components/InputWithPlaceholderSelect.vue
src/components/KeyAndValueEditor.vue
src/hooks/Rule/bridge/useComponentsHandlers.ts

support slot in placeholder select

feat(component): support select placeholder in key value editor

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/components/TLSConfig/TLSEnableConfig.vue
src/hooks/Config/useListenerDialog.ts

https://emqx.atlassian.net/browse/ED-1342

feat(listener): handle verify change to prevent update error

---

package.json
src/api/plugins.ts
src/components/PluginsForm/PluginFormKit.vue
src/hooks/Plugins/avroUtils.ts
src/hooks/Plugins/useRenderPluginForm.ts
src/i18n/Plugins.js
src/views/Plugins/PluginDetail.vue
src/views/Plugins/components/PluginManage.vue
yarn.lock

https://emqx.atlassian.net/browse/ED-1299

feat(plugin): add the config update api

---

src/components/InputWithPlaceholderSelect.vue
src/i18n/LogTrace.js
src/views/Diagnose/LogTrace/LogTrace.vue

https://emqx.atlassian.net/browse/ED-1352

refactor(log trace): form label and order adjustment

---

src/hooks/Rule/bridge/useInfluxdbLineProtocol.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/types/schemas/actions.schemas.ts
src/types/schemas/bridges.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/connectors.schemas.ts
src/types/schemas/messageValidation.schemas.ts
src/types/schemas/metrics.schemas.ts
src/types/schemas/monitor.schemas.ts
src/types/schemas/schemaRegistry.schemas.ts
src/types/schemas/sources.schemas.ts
src/views/RuleEngine/MessageValidation/components/MessageValidationForm.vue
src/views/RuleEngine/MessageValidation/components/SchemaCreateDrawer.vue

https://emqx.atlassian.net/browse/ED-1353
https://emqx.atlassian.net/browse/ED-1351
https://emqx.atlassian.net/browse/ED-1350

fix(action): cnhanced parsing of the influxdb line protocol

---

src/views/General/resource_dict.json
src/views/RuleEngine/MessageValidation/MessageValidation.vue

feature that were missed before

feat(msg validation): table support drag and drop

---

src/i18n/BasicConfig.js
src/i18n/RuleEngine.js
src/views/Auth/components/AuthzManager.vue
src/views/Auth/components/TableDropdown.vue
src/views/RuleEngine/Bridge/Components/DeleteBridgeSecondConfirm.vue

https://emqx.atlassian.net/browse/ED-1358
https://emqx.atlassian.net/browse/ED-1356

fix(source): disable delete source that is being used by rule

---

src/i18n/Function.js

https://emqx.atlassian.net/browse/ED-1360

fix(flow): missing function arguments label

---

src/common/constants.ts
src/components/ObjectArrayEditor.vue
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/views/Config/BasicConfig/Mqtt.vue

https://emqx.atlassian.net/browse/ED-1348

refactor(auth): describe the new supported `${client_attrs.<attribute>} `

---

src/hooks/Auth/useAuthnCreate.ts
src/hooks/Auth/useProcessAuthData.ts
src/i18n/Auth.js
src/views/Auth/components/JwtConfig.vue

https://emqx.atlassian.net/browse/ED-1330

feat(auth): add disconnect after expire on jwt

---

src/hooks/Clients/useClientDetail.ts
src/i18n/Clients.js
src/types/client.d.ts
src/views/Clients/ClientDetails.vue

https://emqx.atlassian.net/browse/ED-1306

feat(client): update client detail view to handle durable sessions

---

src/i18n/General.js
src/i18n/components.js
src/router/index.ts
src/types/config.d.ts
src/views/Config/BasicConfig/SessionPersistence.vue
src/views/General/FlappingDetect.vue

https://emqx.atlassian.net/browse/ED-1363

feat(mqtt): support session persistence configs

---

src/common/constants.ts
src/hooks/Config/useListenerUtils.ts

https://emqx.atlassian.net/browse/ED-1373

feat(listener): add back the zone config to custom configs

---

src/views/Config/BasicConfig/SessionPersistence.vue

https://emqx.atlassian.net/browse/ED-1374

fix(mqtt): add permission control to session persistence

---

src/i18n/General.js
src/views/Config/BasicConfig/SessionPersistence.vue

https://emqx.atlassian.net/browse/ED-1374

fix(mqtt): update session persistence descriptions

---

src/views/RuleEngine/MessageValidation/components/ValidationOverview.vue

https://emqx.atlassian.net/browse/ED-1372

feat(validation): support metrics reset

---

src/common/http.js
src/i18n/Clients.js
src/views/Auth/components/AuthzManager.vue

https://emqx.atlassian.net/browse/ED-1364
https://emqx.atlassian.net/browse/ED-1375
https://emqx.atlassian.net/browse/ED-1376

fix(authz): disabled top and bottom item move buttons

---

src/i18n/Clients.js
src/i18n/RuleEngine.js
src/i18n/RuleEvent.js
src/views/RuleEngine/components/MockDataDrawer.vue
src/views/RuleEngine/components/SQLTest.vue

https://emqx.atlassian.net/browse/ED-1368

fix(rule): some missing or incorrect labels

---

src/types/schemas/messageValidation.schemas.ts
src/views/RuleEngine/MessageValidation/components/MessageValidationForm.vue

https://emqx.atlassian.net/browse/ED-1365

fix(msg validation): issue with adding protobuf type checking

---

src/hooks/Clients/useClientFields.ts
src/views/Clients/ClientDetails.vue

https://emqx.atlassian.net/browse/ED-1377

fix(gateway): hide mqueue and inflight in ocpp

---

src/components/ObjectArrayEditor.vue
src/views/Config/BasicConfig/Mqtt.vue

https://emqx.atlassian.net/browse/ED-1366

fix(mqtt): optimising the width of table column

---

src/hooks/Rule/bridge/useComponentsHandlers.ts

part of 
https://emqx.atlassian.net/browse/ED-1370

fix(action): logic for handling monaco provider

---

src/hooks/Rule/rule/useFormatDebugLog.ts

https://emqx.atlassian.net/browse/ED-1380

fix(rule): handling the case where `trigger_times` has a length greater than 1

---

src/hooks/Rule/bridge/useComponentsHandlers.ts

https://emqx.atlassian.net/browse/ED-1370

fix(action): some fields placeholders are not selectable

---

src/views/RuleEngine/components/LogDataDisplay.vue

https://emqx.atlassian.net/browse/ED-1382

fix(rule): add tooltip for show topic

---

src/views/RuleEngine/components/FromSelect.vue
src/views/RuleEngine/components/MockDataDrawer.vue

https://emqx.atlassian.net/browse/ED-1384
https://emqx.atlassian.net/browse/ED-1383

fix(rule): hide source in `FromSelect`

---

src/style/schemaForm.scss

style(schema): width of the table in schema form

---

src/i18n/RuleEngine.js
src/i18n/RuleEvent.js
src/views/RuleEngine/Connector/Connector.vue
src/views/RuleEngine/SchemaValidation/components/SchemaValidationForm.vue

https://emqx.atlassian.net/browse/ED-1385
https://emqx.atlassian.net/browse/ED-1387
https://emqx.atlassian.net/browse/ED-1386

refactor(rule): rename event message validation to schema validation

---

src/i18n/RuleEngine.js
src/views/RuleEngine/components/RuleForm.vue
src/views/RuleEngine/components/RuleTest.vue
src/views/RuleEngine/components/SQLTest.vue

https://emqx.atlassian.net/browse/ED-1369

fix(rule): stop test if save as copy

---

src/hooks/Rule/rule/useDebugRule.ts
src/hooks/Rule/rule/useFormatDebugLog.ts
src/hooks/Rule/rule/useRuleEvents.ts
src/i18n/Clients.js
src/i18n/RuleEngine.js
src/i18n/RuleEvent.js
src/types/schemas/rules.schemas.ts
src/views/Clients/components/ClientFieldSelect.vue
src/views/RuleEngine/components/MockDataDrawer.vue
src/views/RuleEngine/components/RuleTest.vue

https://emqx.atlassian.net/browse/ED-1378
https://emqx.atlassian.net/browse/ED-1389
https://emqx.atlassian.net/browse/ED-1390
https://emqx.atlassian.net/browse/ED-1391
https://emqx.atlassian.net/browse/ED-1388

fix(plugin): style of table dropdown button

---

src/hooks/Rule/rule/useFormatDebugLog.ts

https://emqx.atlassian.net/browse/ED-1392

fix(rule): filter connector log

---

src/style/common.scss
src/types/schemas/configs.schemas.ts
src/views/Auth/components/DatabaseConfig.vue

https://emqx.atlassian.net/browse/ED-1354

fix(auth): provide option for `use_legacy_protocol`

---

src/hooks/Rule/rule/useFormatDebugLog.ts
src/i18n/RuleEngine.js

https://emqx.atlassian.net/browse/ED-1393

fix(rule): optimized logs when recursion

---

src/i18n/Dashboard.js

fix(dashboard): update email notification

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/i18n/Clients.js
src/i18n/RuleEngine.js
src/i18n/RuleEvent.js
src/i18n/components.js
src/types/schemas/actions.schemas.ts
src/types/schemas/clients.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/metrics.schemas.ts
src/types/schemas/nodes.schemas.ts
src/views/RuleEngine/Schema/components/SchemaRegistryForm.vue

https://emqx.atlassian.net/browse/ED-1401
https://emqx.atlassian.net/browse/ED-1400
[6872101](https://github.com/emqx/emqx-dashboard5/pull/2686/commits/6872101f6b0e837871e00a60aa6d571cdada851b) From PM

fix(schema validation): `Schema 校验` -> `Schema 验证`

---

src/hooks/Rule/rule/useFormatDebugLog.ts

https://emqx.atlassian.net/browse/ED-1394

fix(rule): `rule_trigger_times` -> `rule_trigger_ts`

---

src/hooks/Rule/rule/useFormatDebugLog.ts

https://emqx.atlassian.net/browse/EMQX-12360?focusedCommentId=40183

fix(rule): show original log content for re pub

---

src/hooks/Rule/rule/useFormatDebugLog.ts
src/views/Clients/Clients.vue

https://emqx.atlassian.net/browse/ED-1402

fix(rule): Remove logs that are not rule executions and are without action info

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/views/RuleEngine/components/FromSelect.vue

https://emqx.atlassian.net/browse/ED-1404

refactor(mqtt): desc for `retain_available`

---

src/hooks/Plugins/useRenderPluginForm.ts

https://emqx.atlassian.net/browse/ED-1406

fix(plugin): handle schema without ui config

---

src/components/OneofRefsSelect.vue
src/components/SchemaForm.tsx
src/types/schemaForm.d.ts

refactor(schema form): enhanced schema form

---

package.json
yarn.lock

chore(package): upgrade element-plus

---

src/hooks/Rule/useSQLAvailablePlaceholder.ts

https://emqx.atlassian.net/browse/ED-1410

fix(rule): fixed incorrect support for placeholder

---

package.json
src/hooks/Rule/rule/useDebugRule.ts
src/hooks/Rule/rule/useFormatDebugLog.ts
src/hooks/Rule/useProvidersForMonaco.ts
src/types/schemas/metrics.schemas.ts
src/types/schemas/plugins.schemas.ts
src/views/Flow/FlowHandler.vue
src/views/RuleEngine/Bridge/BridgeDetail.vue
yarn.lock

chore(package): upgrade vue for fix warning

---

src/components/SchemaForm.tsx
src/components/SelectAllowInput.vue
src/hooks/Rule/rule/useRule.ts
src/hooks/Rule/useSQLAvailablePlaceholder.ts
src/views/RuleEngine/Bridge/BridgeCreate.vue
src/views/RuleEngine/components/RePubForm.vue

https://emqx.atlassian.net/browse/ED-1411
https://emqx.atlassian.net/browse/ED-1412

refactor(rule): optimizing the interaction of inputtable select

---

src/hooks/Rule/rule/useRuleEvents.ts
src/i18n/RuleEngine.js
src/i18n/RuleEvent.js
src/types/enum.ts

https://emqx.atlassian.net/browse/ED-1413

fix(rule): adapt new event

---

src/hooks/Rule/useSQLAvailablePlaceholder.ts

https://emqx.atlassian.net/browse/ED-1411

refactor(rule): show supported placeholders when the data source is kafka_consumer, etc

---

src/hooks/Rule/rule/useRule.ts
src/hooks/Rule/useSQLAvailablePlaceholder.ts

https://emqx.atlassian.net/browse/ED-1411

fix(rule): fix the logic for judging the type of data source

---

src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/types/schemas/actions.schemas.ts
src/types/schemas/connectors.schemas.ts

https://emqx.atlassian.net/browse/ED-1420

refactor(connector): new field disable_prepared_statements in pgsql

---

src/views/Settings/Help.vue

https://emqx.atlassian.net/browse/ED-1422

fix(help): remove github platform

---

src/components/SchemaForm.tsx
src/types/schemas/rules.schemas.ts
src/views/RuleEngine/Bridge/BridgeDetail.vue

https://emqx.atlassian.net/browse/ED-1423

fix(schema form): re-fix the logic that handles the selection of oneof ref

---

src/hooks/Rule/useSQLAvailablePlaceholder.ts

https://emqx.atlassian.net/browse/ED-1424

fix(rule): empty placeholder

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/hooks/Config/useListenerDialog.ts

https://emqx.atlassian.net/browse/ED-1430

fix(listener): old data remaining

---

src/components/InputWithPlaceholderSelect.vue
src/components/SelectAllowInput.vue
src/hooks/Rule/bridge/useComponentsHandlers.ts
src/views/RuleEngine/components/RePubForm.vue

part of https://emqx.atlassian.net/browse/ED-1428
https://emqx.atlassian.net/browse/ED-1431

feat(placeholder select): support custom placeholder

---

src/views/Diagnose/components/WebSocketItem.vue
src/views/Gateway/components/coapBasic.vue

https://emqx.atlassian.net/browse/ED-1067
https://emqx.atlassian.net/browse/ED-1042

fix(gateway): can not empty `heartbeat`

---

src/i18n/Clients.js

https://emqx.atlassian.net/browse/ED-1425

fix(client): optimized labels for metrics

---

src/components/CommonOverflowTooltip.vue
src/components/OverflowTooltip.vue
src/components/PreWrap.vue
src/views/Clients/ClientDetails.vue
src/views/Clients/Clients.vue
src/views/Diagnose/TopicMetrics.vue
src/views/Diagnose/components/SlowSubData.vue
src/views/Retained/Retained.vue
src/views/Subscriptions/Subscriptions.vue
src/views/Topics/Topics.vue

https://emqx.atlassian.net/browse/ED-1359
https://emqx.atlassian.net/browse/ED-465

fix(client): some texts cannot be displayed completely when they are too long

---

src/hooks/Config/useListenerDialog.ts
src/hooks/Config/useListenerUtils.ts

https://emqx.atlassian.net/browse/ED-1438

fix(listener): delete cacertfile when it is empty on quic

---

src/types/plugin.d.ts
src/views/Plugins/PluginDetail.vue
src/views/Plugins/components/PluginManage.vue

https://emqx.atlassian.net/browse/ED-1440

fix(plugin): do not request config api with old version pkg

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Rule/useDataHandler.ts
src/i18n/RuleEngine.js
src/schemaText/actionText/action-desc-en.json
src/schemaText/actionText/action-desc-zh.json
src/schemaText/actionText/action-label-en.json
src/schemaText/actionText/action-label-zh.json
src/views/General/resource_dict.json

https://emqx.atlassian.net/browse/ED-1428

fix(action): correct placeholders for `key` in aggregated mode

---

src/components/Oneof.vue
src/components/SchemaForm.tsx
src/components/SchemaFormItem.tsx
src/i18n/Clients.js
src/i18n/Dashboard.js
src/i18n/Tools.js

https://emqx.atlassian.net/browse/ED-1425?focusedCommentId=41080
https://emqx.atlassian.net/browse/ED-1435

refactor(client & overview): text for msg in and msg out

---

src/hooks/Schema/useSchemaFormRules.ts
src/i18n/Dashboard.js

https://emqx.atlassian.net/browse/ED-1447
https://emqx.atlassian.net/browse/ED-1448
https://emqx.atlassian.net/browse/ED-1442

fix(overview): correct some label

---

src/components/ListenerDrawer/CustomConfigs.vue
src/components/ListenerDrawer/ListenerDrawer.vue
src/hooks/Config/useListenerDrawer.ts
src/hooks/Config/useListenerUtils.ts

https://emqx.atlassian.net/browse/ED-1443

feat(listener): support reset default value on custom configs

---

src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts

https://emqx.atlassian.net/browse/ED-1449

refactor(connector): move `disable_prepared_statements` to advanced settings in pgsql

---

src/hooks/Rule/transform/useMessageTransform.ts
src/views/RuleEngine/MessageTransform/TransformDetail.vue
src/views/RuleEngine/MessageTransform/components/TransformForm.vue
src/views/RuleEngine/MessageTransform/components/TransformOverview.vue

https://emqx.atlassian.net/browse/ED-1416

refactor(msg transform): fix some types and add missing rules

---

src/views/Config/BasicConfig/Mqtt.vue

https://emqx.atlassian.net/browse/ED-1452

fix(mqtt): remove unit `GB` for `max_packet_size`

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/components/Oneof.vue
src/components/SchemaForm.tsx

https://emqx.atlassian.net/browse/ED-1456

fix(listener): adapt the infinity rate

---

src/i18n/Base.js
src/i18n/Dashboard.js
src/views/Dashboard/components/PolylineCards.vue
src/views/Dashboard/components/PolylineChart.vue

https://emqx.atlassian.net/browse/ED-1455

feat(overview): chart supports zoom in/out to full screen

---

src/views/Clients/components/MessageListDialog.vue

https://emqx.atlassian.net/browse/ED-1458

fix(client): handling data duplication when the list is too short

---

src/hooks/SSO/useSSO.ts
src/views/RuleEngine/components/RuleInputs.vue

https://emqx.atlassian.net/browse/ED-1459

fix(sso): add label for oidc

---

src/views/Clients/components/MessageListDialog.vue

https://emqx.atlassian.net/browse/ED-1460

fix(client): display of message queue info when it is too long

---

src/i18n/RuleEngine.js
src/style/common.scss
src/views/RuleEngine/MessageTransform/components/OperationsTable.vue
src/views/RuleEngine/MessageTransform/components/TargetValue.vue
src/views/RuleEngine/MessageTransform/components/TransformForm.vue
src/views/RuleEngine/SchemaValidation/components/SchemaValidationForm.vue
src/views/RuleEngine/components/SQLContentDialog.vue

https://emqx.atlassian.net/browse/ED-1461

fix(msg transform): some issues

---

src/i18n/General.js

https://emqx.atlassian.net/browse/ED-1462

fix(sso): correct chinese label in oidc

---

src/components/CustomFormItem.vue
src/components/KeyAndValueEditor.vue
src/components/Metrics/OverviewMetrics.vue
src/components/OneofRefs.vue
src/components/OneofRefsSelect.vue
src/components/TLSConfig/TLSEnableConfig.vue
src/hooks/Auth/useAuthn.ts
src/hooks/Auth/useAuthz.ts
src/hooks/Auth/useHTTPConfigForm.ts
src/hooks/Auth/useLdapConfigForm.ts
src/hooks/useClusterNodes.ts
src/hooks/usePagination.ts
src/hooks/usePaginationWithHasNext.ts
src/hooks/usePassword.ts
src/hooks/useShowTextByDifferent.ts
src/hooks/useSortableTable.ts
src/i18n/Clients.js
src/types/schemas/authentication.schemas.ts
src/types/schemas/authorization.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/gatewayAuthentication.schemas.ts
src/types/schemas/gatewayListeners.schemas.ts
src/views/Clients/ClientDetails.vue

https://emqx.atlassian.net/browse/ED-1457

fix(client): rename Reductions to Erlang Reduction

---

src/i18n/RuleEngine.js
src/types/schemas/actions.schemas.ts
src/types/schemas/authentication.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/connectors.schemas.ts
src/types/schemas/dashboard.schemas.ts
src/types/schemas/dataBackup.schemas.ts
src/types/schemas/gatewayAuthentication.schemas.ts
src/types/schemas/gatewayListeners.schemas.ts
src/types/schemas/listeners.schemas.ts
src/types/schemas/messageTransformation.schemas.ts
src/types/schemas/schemaRegistry.schemas.ts
src/types/schemas/schemaValidation.schemas.ts
src/types/schemas/sources.schemas.ts
src/views/RuleEngine/MessageTransform/TransformCreate.vue
src/views/RuleEngine/MessageTransform/components/TargetValue.vue
src/views/RuleEngine/MessageTransform/components/TransformForm.vue

https://emqx.atlassian.net/browse/ED-1467

fix(msg transform): delete `schema` after type changed

---

src/hooks/Auth/useAuthnCreate.ts
src/hooks/Auth/useProcessAuthData.ts
src/views/Auth/components/JwtConfig.vue

https://emqx.atlassian.net/browse/ED-1468

feat(auth): jwks support headers config

---

src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json

https://emqx.atlassian.net/browse/ED-1466

fix(mqtt): adapt `keepalive_check_interval`

---

src/i18n/Clients.js
src/i18n/RuleEngine.js

https://emqx.atlassian.net/browse/ED-1471
https://emqx.atlassian.net/browse/ED-1469

fix(msg transform): correct some text

---

src/common/constants.ts
src/hooks/Rule/transform/useMessageTransform.ts
src/views/RuleEngine/MessageTransform/TransformCreate.vue
src/views/RuleEngine/MessageTransform/TransformDetail.vue
src/views/RuleEngine/MessageTransform/components/OperationsTable.vue
src/views/RuleEngine/MessageTransform/components/TransformForm.vue
src/views/RuleEngine/components/SQLContentDialog.vue

https://emqx.atlassian.net/browse/ED-1461   point 3
https://emqx.atlassian.net/browse/ED-1470
https://emqx.atlassian.net/browse/ED-1474
https://emqx.atlassian.net/browse/ED-1473

fix(msg transform): styling issue after opening dialog

---

src/hooks/Auth/useProcessAuthData.ts

https://emqx.atlassian.net/browse/ED-1476

fix(authn): set headers when type is JWKS

---

src/i18n/Clients.js

https://emqx.atlassian.net/browse/ED-1471

fix(rule): correct label of `transformation` in rule test

---

src/i18n/Dashboard.js
src/views/Base/Layout.vue
src/views/Base/LicenseTipDialog.vue

https://emqx.atlassian.net/browse/ED-1479

refactor(license): do not allow the license popup to be permanently closed

---

src/hooks/Rule/transform/useMessageTransform.ts

https://emqx.atlassian.net/browse/ED-1470

refactor(msg transform): allowed use of attrs under the pub props

---

src/api/hotUpgrade.ts
src/views/General/HotUpgrade.vue
src/views/General/components/UpgradeNodeDialog.vue
src/views/General/components/UpgradeRecordsDialog.vue

Could I just unlimit the timeout for these requests?

refactor(hot upgrade): set special timeout for some request

---

src/common/docLinks.ts

https://emqx.atlassian.net/browse/ED-1481

fix(docs): update doc links

---

src/api/cluster.ts
src/components/OverflowTooltip.vue
src/hooks/Config/useClusterLinking.ts
src/hooks/useMenus.ts
src/i18n/BasicConfig.js
src/i18n/components.js
src/router/index.ts
src/style/common.scss
src/types/schemas/cluster.schemas.ts
src/types/typeAlias.ts
src/views/Config/ClusterLinking/ClusterLinking.vue
src/views/Config/ClusterLinking/components/ClusterLinkingDialog.vue
src/views/RuleEngine/MessageTransform/MessageTransform.vue
src/views/RuleEngine/SchemaValidation/SchemaValidation.vue

https://emqx.atlassian.net/browse/ED-1432

Cluster Linking

---

src/components/FormItemLabel.vue
src/hooks/Auth/useAuthnCreate.ts
src/hooks/Rule/transform/useMessageTransform.ts
src/i18n/Auth.js
src/types/schemas/authentication.schemas.ts
src/types/schemas/gatewayListeners.schemas.ts
src/types/schemas/gateways.schemas.ts
src/types/schemas/messageTransformation.schemas.ts
src/types/schemas/rules.schemas.ts
src/views/Auth/AuthnCreate.vue
src/views/Auth/components/BuiltInConfig.vue
src/views/Auth/components/HttpConfig.vue
src/views/RuleEngine/MessageTransform/TransformDetail.vue

https://emqx.atlassian.net/browse/ED-1483

feat(authn): adapt enhanced http authn

---

src/hooks/Rule/action/useHandleSourceItem.ts
src/hooks/Rule/bridge/useDeleteBridge.ts
src/hooks/Rule/connector/useHandleConnectorItem.ts
src/hooks/Rule/rule/useDebugRule.ts
src/hooks/Rule/rule/useRule.ts
src/i18n/RuleEngine.js
src/style/rule.scss
src/types/rule.d.ts
src/views/RuleEngine/Bridge/DataBridge.vue
src/views/RuleEngine/Connector/Connector.vue
src/views/RuleEngine/Connector/ConnectorDetail.vue
src/views/RuleEngine/Connector/components/DelConnectorTip.vue
src/views/RuleEngine/Connector/components/DisableConnectorConfirm.vue
src/views/RuleEngine/Rule/Rule.vue
src/views/RuleEngine/Rule/RuleDetail.vue
src/views/RuleEngine/Rule/components/DeleteRuleConfirm.vue
src/views/RuleEngine/Rule/components/RuleFilterForm.vue
src/views/RuleEngine/Source/Source.vue
src/views/RuleEngine/components/RuleOutputs.vue
src/views/RuleEngine/components/SQLTest.vue

https://emqx.atlassian.net/browse/ED-1465

refactor(rule): supports delete action & rule used by rules at the same time

---

src/i18n/LogTrace.js
src/i18n/Tools.js
src/types/schemas/gatewayListeners.schemas.ts
src/types/schemas/gateways.schemas.ts
src/types/schemas/rules.schemas.ts

https://emqx.atlassian.net/browse/ED-1486
https://emqx.atlassian.net/browse/ED-1488

fix(topic metrics): correct metrics label

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/hooks/useMenus.ts

https://emqx.atlassian.net/browse/ED-1489
connector and source

refactor(connector & source): adapt new fields

---

src/hooks/Auth/useAuthzCreate.ts
src/i18n/Auth.js
src/views/Auth/AuthnCreate.vue
src/views/Auth/AuthnDetails.vue
src/views/Auth/Authz.vue
src/views/Auth/AuthzCreate.vue
src/views/Auth/AuthzDetails.vue
src/views/Auth/components/BuiltInConfig.vue
src/views/Auth/components/TableDropdown.vue

https://emqx.atlassian.net/browse/ED-1489 
authz

refactor(authz): support config `max_rules` in type built in data base

---

src/views/Config/ClusterLinking/components/ClusterLinkingDialog.vue
src/views/Flow/components/form/processing/FunctionBlock.vue
src/views/Flow/components/form/processing/FunctionForm.vue

https://emqx.atlassian.net/browse/ED-1344

refactor(flow): layout of form for data processing node

---

src/components/Metrics/TypeMetricsItem.vue
src/hooks/Flow/useFlowNode.ts
src/hooks/Rule/rule/useRule.ts

https://emqx.atlassian.net/browse/ED-1495

fix(flow): inconsistent icon sizes

---

src/views/Auth/AuthnCreate.vue
src/views/Flow/components/form/processing/FunctionBlock.vue

https://emqx.atlassian.net/browse/ED-1496

fix(authn): add back LDAP

---

src/components/Metrics/OverviewMetrics.vue
src/hooks/useMetrics.ts
src/i18n/Auth.js

https://emqx.atlassian.net/browse/ED-1478

refactor(authz): adapt new metric item ignore

---

src/hooks/Rule/transform/useMessageTransform.ts
src/hooks/useMetrics.ts

https://emqx.atlassian.net/browse/ED-1499

fix(msg transform): remove User-Property-Pairs in pub props

---

src/hooks/useAdaptiveEditor.ts
src/views/Auth/components/FileConfig.vue

https://emqx.atlassian.net/browse/ED-1498

feat(auth): acl editor can auto adapt

---

src/views/Flow/components/form/processing/FunctionForm.vue

https://emqx.atlassian.net/browse/ED-1344

fix(flow): function node form action column display error

---

src/hooks/useMenus.ts
src/router/index.ts
src/views/Auth/AuthnDetails.vue

https://emqx.atlassian.net/browse/ED-1503
https://emqx.atlassian.net/browse/ED-1477

fix(authn): some fields do not show when editing

---

src/views/RuleEngine/components/RuleInputs.vue

https://emqx.atlassian.net/browse/ED-1506

fix(rule): bug when deleting input

---

src/hooks/Rule/rule/useDebugRule.ts
src/store/index.ts
src/views/RuleEngine/Rule/RuleCreate.vue
src/views/RuleEngine/Rule/RuleDetail.vue
src/views/RuleEngine/components/LogDataDisplay.vue
src/views/RuleEngine/components/RuleForm.vue
src/views/RuleEngine/components/RuleTest.vue

https://emqx.atlassian.net/browse/ED-1484

refactor(overview metrics): structure of metrics data

---

src/hooks/useMenus.ts
src/router/index.ts

This reverts commit 8ac5114a764500e769c1a304157cd94772c7642f.

Revert "fix(msg transform): hide msg transform first"

---

src/hooks/Rule/useDataHandler.ts

https://emqx.atlassian.net/browse/ED-1465

fix(action): remove `rules` field when submitting

---

src/i18n/Auth.js

https://emqx.atlassian.net/browse/ED-1512

fix(authz): update ignore desc

---

.github/workflows/build_emqx_for_test.yaml
src/hooks/Rule/useDataHandler.ts
src/hooks/useMenus.ts
src/types/schemas/actions.schemas.ts
src/types/schemas/authorization.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/rules.schemas.ts
src/types/schemas/sources.schemas.ts

https://emqx.atlassian.net/browse/ED-1513
https://emqx.atlassian.net/browse/ED-1514

fix(menu): topic metrics in menu

---

src/hooks/useMenus.ts
src/router/index.ts
src/views/Base/Login.vue
src/views/General/SSO.vue
src/views/RuleEngine/MessageTransform/components/TransformForm.vue

https://emqx.atlassian.net/browse/ED-1511

fix(msg transform): operation's validation result does not disappear

---

src/hooks/Overview/useNodesGraph.ts
src/views/Dashboard/components/CoreNode.vue
src/views/RuleEngine/Rule/components/DeleteRuleConfirm.vue
src/views/RuleEngine/components/RePubForm.vue

https://emqx.atlassian.net/browse/ED-1501
https://emqx.atlassian.net/browse/ED-1502
https://emqx.atlassian.net/browse/ED-1501

style(rule): styles of confirmation popups for deletion rule

---

src/views/Topics/Topics.vue

https://emqx.atlassian.net/browse/ED-1515

fix(topics): button that shouldn't be there

---

src/views/Auth/components/DatabaseConfig.vue
src/views/Auth/components/HttpConfig.vue

https://emqx.atlassian.net/browse/ED-1492

refactor(auth): moving some fields to advanced settings

---

src/hooks/Rule/transform/useMessageTransform.ts

https://emqx.atlassian.net/browse/ED-1517

fix(msg transform): missing `pub_props`

---

src/components/PluginsForm/PluginFormKitItem.vue
src/hooks/Plugins/useRenderPluginForm.ts
src/types/plugin.d.ts

https://emqx.atlassian.net/browse/ED-1507

refactor(plugin): support for parameter ordering

---

src/common/constants.ts
src/common/http.js
src/components/AdvancedSettingContainer.vue
src/components/AdvancedSettingsBtn.vue

https://emqx.atlassian.net/browse/ED-1521

refactor(http): optimize http error msg

---

src/hooks/Flow/useGenerateFlowDataUtils.ts
src/hooks/Flow/useHandleFlowDataUtils.ts
src/hooks/Rule/RuleFunc.json
src/hooks/useRuleFunc.ts

https://emqx.atlassian.net/browse/ED-1534

fix(flow): add single quotes if the type of function parameter is string

---

src/hooks/Rule/transform/useMessageTransform.ts
src/views/General/components/UpgradeNodeDialog.vue
src/views/RuleEngine/components/RuleTest.vue

https://emqx.atlassian.net/browse/ED-1525
https://emqx.atlassian.net/browse/ED-1530
https://emqx.atlassian.net/browse/ED-1536

fix(msg transform): change `payload.` to `payload.*`

---

src/components/Metrics/OverviewMetrics.vue
src/hooks/useMetrics.ts

refactor(metrics): use `get` to get metric item

---

src/hooks/useMetrics.ts
src/views/Config/ClusterLinking/ClusterLinkingDetail.vue
src/views/Exhook/ExhookDetail.vue
src/views/RuleEngine/MessageTransform/TransformDetail.vue
src/views/RuleEngine/SchemaValidation/ValidationDetail.vue

https://emqx.atlassian.net/browse/ED-1532

fix(msg transform etc.): inconsistent styling of detail page header

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/i18n/RuleEngine.js
src/views/General/components/UpgradeNodeDialog.vue

https://emqx.atlassian.net/browse/ED-1536
https://emqx.atlassian.net/browse/ED-1526

fix(hot upgrade): show loading status when uploading

---

src/components/Metrics/OverviewMetrics.vue

refactor(overview metrics): use `get` to get rate metrics

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/hooks/Config/useListenerDrawer.ts
src/hooks/Config/useListenerUtils.ts
src/i18n/Gateway.js
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/types/schemas/configs.schemas.ts

https://emqx.atlassian.net/browse/ED-1509
https://emqx.atlassian.net/browse/ED-1508
https://emqx.atlassian.net/browse/ED-1543

feat(gateway): support config `health_check` in CoAP listener

---

src/components/Metrics/OverviewMetrics.vue
src/hooks/useMetrics.ts

refactor(metrics): add colors

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/useMetrics.ts
src/i18n/BasicConfig.js
src/i18n/RuleEngine.js
src/views/Config/ClusterLinking/components/ClusterLinkingOverview.vue

refactor(cluster linking): show linking metrics

---

src/views/Auth/components/AuthzManager.vue

https://emqx.atlassian.net/browse/ED-1547

fix(authz): error after failed submission

---

src/hooks/Auth/useAuthnCreate.ts
src/hooks/Auth/useKerberosConfigForm.ts
src/i18n/Auth.js
src/views/Auth/components/KerberosConfig.vue

https://emqx.atlassian.net/browse/ED-1541

fix(authn): remove keytab_file config item

---

src/hooks/useMetrics.ts
src/i18n/BasicConfig.js
src/views/RuleEngine/MessageTransform/components/TargetValue.vue

https://emqx.atlassian.net/browse/ED-1553

fix(msg transform): prop not being cleared

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/i18n/Gateway.js

https://emqx.atlassian.net/browse/ED-1540

fix(listener): add help-text for rate limiter

---

src/i18n/Auth.js

https://emqx.atlassian.net/browse/ED-1541

fix(auth): fix principal tips format error

---

src/views/General/HotUpgrade.vue
src/views/General/components/UpgradeNodeDialog.vue

https://emqx.atlassian.net/browse/ED-1555

fix(hot upgrade): request that cannot be canceled

---

src/i18n/RuleEngine.js
src/types/schemas/rules.schemas.ts
src/views/RuleEngine/components/RePubForm.vue
src/views/RuleEngine/components/RuleOutputsDrawer.vue

https://emqx.atlassian.net/browse/ED-1548

fix(rule): direct dispatch support in repub action

---

src/views/Flow/FlowHandler.vue
src/views/Flow/components/FlowEditor.vue

https://emqx.atlassian.net/browse/ED-1558
https://emqx.atlassian.net/browse/ED-1557

fix(flow): incorrect error msg; disappearing guides

---

src/api/clients.ts
src/components/CodeView.vue
src/views/Clients/Clients.vue

https://emqx.atlassian.net/browse/ED-1528
https://emqx.atlassian.net/browse/ED-1535

refactor(clients): exact client id query

---

src/i18n/Gateway.js

https://emqx.atlassian.net/browse/ED-1559

fix(listener): update rate limiter description

---

src/i18n/Auth.js
src/i18n/RuleEngine.js
src/types/schemas/authentication.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/connectors.schemas.ts
src/types/schemas/gatewayAuthentication.schemas.ts
src/types/schemas/gatewayListeners.schemas.ts
src/views/Auth/AuthnCreate.vue

https://emqx.atlassian.net/browse/ED-1548
https://emqx.atlassian.net/browse/ED-1565

fix(rule): direct dispatch help-text update

---

src/i18n/RuleEngine.js
src/types/schemas/messageTransformation.schemas.ts
src/views/RuleEngine/MessageTransform/components/TestDrawer.vue
src/views/RuleEngine/components/PubProps.vue
src/views/RuleEngine/components/RePubForm.vue

https://emqx.atlassian.net/browse/ED-1552

fix(msg transform): missing attributes for testing

---

src/views/Auth/AuthnDetails.vue

https://emqx.atlassian.net/browse/ED-1567

fix(auth): fix missing kerberos config on settings

---

yarn.lock

https://emqx.atlassian.net/browse/ED-1518

chore(dep): upgrade shared-ui-i18n

---

src/views/RuleEngine/MessageTransform/TransformCreate.vue
src/views/RuleEngine/MessageTransform/TransformDetail.vue
src/views/RuleEngine/MessageTransform/components/TestDrawer.vue

https://emqx.atlassian.net/browse/ED-1571

fix(message): fix permission check missing for test button

---

src/hooks/Flow/useFlowNode.ts
src/hooks/Flow/useNodeDrawer.ts
src/hooks/Flow/useNodeForm.ts
src/hooks/Rule/bridge/useBridgeFormCreator.ts
src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/views/Flow/components/NodeDrawer.vue
src/views/RuleEngine/Bridge/BridgeCreate.vue
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/BridgeInfluxdbConfig.vue

https://emqx.atlassian.net/browse/ED-1574

fix(action): issue when creating datalayers action

---

src/views/Plugins/PluginDetail.vue
src/views/Plugins/components/PluginManage.vue

https://emqx.atlassian.net/browse/ED-1579

fix(plugin): fix can not show the no-config plugin ui

---

src/i18n/RuleEngine.js
src/views/RuleEngine/components/RePubForm.vue

https://emqx.atlassian.net/browse/ED-1576

fix(rule): improve the option for payload format indicator

---

src/common/docLinks.ts
src/components/BatchSettings.vue
src/types/enum.ts
src/views/Diagnose/SlowSub.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbFieldsEditor.vue
src/views/RuleEngine/Bridge/Components/BridgeConfig/InfluxdbLineProtocolForm.vue

https://emqx.atlassian.net/browse/ED-1577

fix(action): batch settings in datalayers

---

src/common/docLinks.ts
src/components/SchemaForm.tsx
src/components/SchemaFormItem.tsx
src/components/TLSConfig/TLSEnableConfig.vue
src/hooks/Rule/action/useHandleActionItem.ts
src/hooks/Rule/action/useHandleSourceItem.ts
src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/bridge/useSpecialRuleForPassword.ts
src/hooks/Schema/useSchemaForm.ts
src/views/Base/Login.vue
src/views/Clients/Clients.vue
src/views/RuleEngine/Connector/ConnectorCreate.vue

https://emqx.atlassian.net/browse/ED-1564
https://emqx.atlassian.net/browse/ED-1580

fix(clients): styling issue in filters

---

src/common/http.js

https://emqx.atlassian.net/browse/ED-1583

fix(http): return reject when error code is canceled

---

src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/hooks/Rule/connector/useComponentsHandlers.ts
src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/hooks/Rule/connector/useSecondRefControl.ts
src/hooks/useFillNewRecord.ts
src/types/schemas/actions.schemas.ts
src/types/schemas/authentication.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/connectors.schemas.ts
src/views/General/Backup.vue
src/views/RuleEngine/Connector/components/ConnectorSchemaForm.vue

https://emqx.atlassian.net/browse/ED-1573
https://emqx.atlassian.net/browse/ED-1583

refactor(connector): adapt new configs in iotdb

---

src/i18n/Dashboard.js
src/types/enum.ts
src/views/Dashboard/components/PolylineCards.vue
src/views/Dashboard/components/PolylineChart.vue
src/views/RuleEngine/Rule/components/DeleteRuleConfirm.vue

https://emqx.atlassian.net/browse/ED-1510

feat(overview): support view live connections

---

src/hooks/Webhook/useWebhookForm.ts
src/types/rule.d.ts
src/views/Webhook/WebhookCreate.vue
src/views/Webhook/WebhookDetail.vue

https://emqx.atlassian.net/browse/ED-1591

fix(webhook): keep headers consistent for action and connector

---

src/hooks/useClusterNodes.ts
src/views/Dashboard/components/NodesGraphCard.vue

https://emqx.atlassian.net/browse/ED-1590

feat(overview): show cluster name

---

yarn.lock

https://emqx.atlassian.net/browse/ED-1578
https://emqx.atlassian.net/browse/ED-790

chore(package): upgrade i18n

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/types/enum.ts

https://emqx.atlassian.net/browse/ED-1603

fix(snowflake): update the private key component

---

src/hooks/useMetrics.ts
src/i18n/RuleEngine.js

https://emqx.atlassian.net/browse/ED-1598

feat(rule): add the discarded action metrics

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts

https://emqx.atlassian.net/browse/ED-1600

feat(kafka): move max linger time and bytes to advanced

---

src/common/jsonUtils.ts
src/views/RuleEngine/components/SQLTest.vue

https://emqx.atlassian.net/browse/ED-1601
https://github.com/emqx/emqx/issues/13785

fix(sql): fix can not handle big float number

---

package.json
pnpm-lock.yaml
scripts/checkAuditDict.js
scripts/checkPermission.js
src/common/constants.ts
src/hooks/Flow/useFlowNode.ts
src/style/common.scss
src/views/Alarm/CurrentAlarm.vue
src/views/Alarm/HistoryAlarm.vue
src/views/Base/QuickPanel.vue
src/views/Diagnose/components/SlowSubData.vue
src/views/Flow/Index.vue
src/views/Flow/components/FlowEditor.vue
src/views/Flow/components/FlowGuide.vue
src/views/Flow/components/FlowView.vue
src/views/Flow/components/form/processing/FunctionForm.vue
src/views/General/AuditLog.vue
src/views/General/Backup.vue
src/views/General/SSO.vue
src/views/General/components/UpgradeNodeDialog.vue
src/views/General/components/UpgradeRecordsDialog.vue

https://emqx.atlassian.net/browse/ED-1585
https://emqx.atlassian.net/browse/ED-1586

refactor(global): use dayjs instead of moment

---

src/common/http.ts
src/style/normalize.scss
src/views/Base/QuickPanel.vue

https://emqx.atlassian.net/browse/ED-1585
https://emqx.atlassian.net/browse/ED-1586

style(message): style issue

---

src/common/constants.ts
src/views/General/BannedClient.vue
src/views/General/components/BannedDialog.vue

https://emqx.atlassian.net/browse/ED-1616

fix(banned): adapt infinity

---

src/common/docLinks.ts
src/hooks/Flow/useFlowNode.ts
src/hooks/Rule/bridge/useBridgeTypeValue.ts
src/types/schemas/actions.schemas.ts
src/types/schemas/connectors.schemas.ts
yarn.lock

https://emqx.atlassian.net/browse/ED-1577
https://emqx.atlassian.net/browse/ED-1617

fix(action): doc link to batch settings

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts

https://emqx.atlassian.net/browse/ED-1623

refactor(action): adapt new field `undefined_vars_as_null`

---

src/components/OverflowTooltip.vue
src/views/RuleEngine/Connector/ConnectorDetail.vue

https://emqx.atlassian.net/browse/ED-1619

fix(connector): incomplete display

---

src/i18n/RuleEngine.js
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/views/RuleEngine/Connector/components/ConnectorSchemaForm.vue
src/views/RuleEngine/Schema/ExternalSchemaDetail.vue
src/views/RuleEngine/Schema/components/ExternalSchemaForm.vue
yarn.lock

https://emqx.atlassian.net/browse/ED-1624
https://emqx.atlassian.net/browse/ED-1622
https://emqx.atlassian.net/browse/ED-1618

fix(connector): bug when copying IoTDB thrift connector

---

src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/types/schemas/actions.schemas.ts
src/types/schemas/connectors.schemas.ts
yarn.lock

https://emqx.atlassian.net/browse/ED-1629
I'm not sure if I should put this field in the advanced settings

refactor(connector): pull new field `recv_timeout` to advanced configs

---

src/components/PayloadDialog.vue
src/views/Auth/components/AuthnUsersImport.vue
src/views/Auth/components/AuthzManager.vue
src/views/General/Users.vue

https://emqx.atlassian.net/browse/ED-1570

fix(users): incorrect styling of password hint during user creation

---

src/views/Dashboard/components/PolylineCards.vue

https://emqx.atlassian.net/browse/ED-1634

fix(overview): filter out invalid data

---

src/i18n/Auth.js

https://emqx.atlassian.net/browse/ED-1633

fix(authn): missing some supported variables in info of client_info

---

src/views/RuleEngine/Bridge/DataBridge.vue
src/views/RuleEngine/Connector/Connector.vue
src/views/RuleEngine/Source/Source.vue

https://emqx.atlassian.net/browse/ED-1637

refactor(connector): show description in table

---

src/App.vue
src/hooks/useDashboardVersion.ts

https://emqx.atlassian.net/browse/ED-1638
@0721Betty FYI

feat(global): print dashboard version in browser console

---

src/views/Auth/AuthnDetails.vue

https://emqx.atlassian.net/browse/ED-1640

fix(authn): authn detail page mechanism shows value

---

src/views/RuleEngine/Rule/components/RuleFilterForm.vue

https://emqx.atlassian.net/browse/ED-1641

fix(rule): style issue in action select

---

src/views/Auth/components/CInfoConfig.vue

https://emqx.atlassian.net/browse/ED-1642

fix(authn): wrong prompt in Client Info

---

src/api/auth.ts
src/i18n/Auth.js
src/i18n/Base.js
src/types/auth.d.ts
src/views/Auth/components/AuthnUsersImport.vue

https://emqx.atlassian.net/browse/ED-1647

feat(authn): show import user result

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
yarn.lock

https://emqx.atlassian.net/browse/ED-1650

refactor(action): adapt new field in kafka consumer

---

src/i18n/Extension.js
src/types/extension.d.ts
src/types/schemas/retainer.schemas.ts
src/views/Config/BasicConfig/Retainer.vue
src/views/Dashboard/Nodes.vue

https://emqx.atlassian.net/browse/ED-1648
https://emqx.atlassian.net/browse/ED-1649

refactor(retainer): adapt new configs

---

src/common/constants.ts
src/i18n/Dashboard.js
src/views/Gateway/components/auth.vue

https://emqx.atlassian.net/browse/ED-1653
https://emqx.atlassian.net/browse/ED-1644

refactor(gateway): positive filtering available mechanism types

---

src/views/Clients/Clients.vue

https://emqx.atlassian.net/browse/ED-1655

fix(clients): label for filtering options

---

package.json
src/components/MarkdownContent.vue
src/style/schemaForm.scss
yarn.lock

https://emqx.atlassian.net/browse/ED-1045

style(markdown): import github-markdown-css

---

package.json
src/api/common.ts
src/common/http.js
src/common/tools.ts
src/components/MarkdownContent.vue
src/style/schemaForm.scss
yarn.lock

https://emqx.atlassian.net/browse/ED-1654
https://emqx.atlassian.net/browse/ED-1045

refactor(global): remove spaces before and after form values

---

pnpm-lock.yaml
src/components/Monaco.vue
src/hooks/Rule/rule/useRule.ts

https://emqx.atlassian.net/browse/ED-487

fix(rule): highlighting of rule sql

---

src/common/http.js
src/hooks/useDashboardVersion.ts

https://emqx.atlassian.net/browse/ED-1660

fix(http): judgement before trim spaces

---

src/hooks/useMetrics.ts
src/views/Clients/Clients.vue

https://emqx.atlassian.net/browse/ED-1662
https://emqx.atlassian.net/browse/ED-1663

fix(action): round to two decimal places for size

---

src/views/Config/BasicConfig/Retainer.vue

https://emqx.atlassian.net/browse/ED-1665

fix(retainer): add rule for `msg_expiry_interval_override`

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Rule/connector/useCheckIoTDBConnectorDriver.ts
src/hooks/Rule/useDataHandler.ts

https://emqx.atlassian.net/browse/ED-1664

fix(action): set `query_mode` to sync if selected thrift connector

---

src/hooks/useDroppedDetail.ts

https://emqx.atlassian.net/browse/ED-1652

style(dropped): style of charts in dark mode

---

src/views/Clients/ClientDetails.vue

https://emqx.atlassian.net/browse/ED-1673
@0721Betty fixed, FYI

fix(gateway): not allow operate subscription for some gateway

---

src/common/constants.ts

https://emqx.atlassian.net/browse/ED-1676

fix(listener): repeated configs in custom configs

---

src/i18n/Gateway.js
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/types/schemas/configs.schemas.ts
src/types/schemas/gatewayListeners.schemas.ts
src/types/schemas/gateways.schemas.ts
src/types/schemas/listeners.schemas.ts
src/views/Gateway/components/coapBasic.vue

https://emqx.atlassian.net/browse/ED-1677
https://emqx.atlassian.net/browse/ED-1678

fix(gateway): desc for `connection_required` in CoAP

---

src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json
src/types/schemas/bridges.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/connectors.schemas.ts
src/types/schemas/dataBackup.schemas.ts
src/types/schemas/fileTransfer.schemas.ts
src/types/schemas/schemaRegistry.schemas.ts
src/types/schemas/sources.schemas.ts
src/views/Config/FileTransfer.vue
yarn.lock

https://emqx.atlassian.net/browse/ED-1679
This new configuration, I'm not sure if it's correct to put it here, please confirm
https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html

fix(connector): adapt new field `access_method` in S3

---

src/hooks/Rule/connector/useComponentsHandlers.ts
src/i18n/components.js

https://emqx.atlassian.net/browse/ED-1688
https://emqx.atlassian.net/browse/ED-1693

fix(connector): can change `verify` in azure

---

src/hooks/Rule/connector/useComponentsHandlers.ts

https://emqx.atlassian.net/browse/ED-1688

fix(connector): do not disable the `ssl.enable`

---

src/components/FormItemLabel.vue
src/components/ListenerDrawer/ListenerDrawer.vue
src/i18n/Gateway.js
src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json

https://emqx.atlassian.net/browse/ED-1692

fix(mqtt & listener): update desc from emqx

---

src/views/Config/Monitoring/MonitoringIntegration.vue

https://emqx.atlassian.net/browse/ED-1696

fix(monitoring integration): correct error msg

---

src/i18n/Gateway.js

https://emqx.atlassian.net/browse/ED-1694

fix(listener): desc for mountpoint

---

src/components/InputWithUnit.vue
src/views/RuleEngine/components/SQLTest.vue

https://emqx.atlassian.net/browse/ED-1695
https://emqx.atlassian.net/browse/ED-1698

fix(component): not allow input negative number for InputWithUnit

---

src/hooks/Rule/rule/useRule.ts
src/style/rule.scss
src/views/RuleEngine/components/RuleInputs.vue
src/views/RuleEngine/components/RuleOutputs.vue

https://emqx.atlassian.net/browse/ED-1680

fix(rule): support jump to action detail page

---

src/components/CustomInputPassword.vue
src/components/ListenerDrawer/ListenerDrawer.vue
src/components/SchemaForm.tsx
src/components/global-components.ts
src/main.ts

https://emqx.atlassian.net/browse/ED-1686
https://emqx.atlassian.net/browse/ED-1700

fix(listener & connector): optimize view password

---

yarn.lock

https://emqx.atlassian.net/browse/ED-1699

refactor(package): upgrade shared-i18n

---

src/views/RuleEngine/Schema/components/SchemaRegistryForm.vue

https://emqx.atlassian.net/browse/ED-1697

fix(schema): validate schema after generate from JSON

---

src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/hooks/Rule/useDataHandler.ts

https://emqx.atlassian.net/browse/ED-1702
@0721Betty Thanks for catching the issue

fix(connector): export ssl configs for thrift IoTDB connector

---

src/api/common.ts
src/components/Metrics/TypeMetricsItem.vue
src/i18n/Dashboard.js
src/views/Dashboard/components/PolylineCards.vue

https://emqx.atlassian.net/browse/ED-1704

fix(action): style of detail tooltip

---

src/api/common.ts
src/common/http.ts
src/i18n/Auth.ts
src/i18n/Base.ts
src/i18n/Dashboard.ts
src/i18n/Extension.ts
src/i18n/General.ts
src/views/Base/Login.vue
src/views/Config/BasicConfig/Retainer.vue

https://emqx.atlassian.net/browse/ED-1682

refactor(login): need change password if password is expired

---

src/style/rule.scss
src/views/RuleEngine/Bridge/BridgeDetail.vue

https://emqx.atlassian.net/browse/ED-1708

fix(actions): fix title name too long issue

---

src/hooks/Rule/bridge/useComponentsHandlers.ts

https://emqx.atlassian.net/browse/ED-1684

refactor(schema): handle boolean type field with is_template

---

src/hooks/Rule/useDataHandler.ts

https://emqx.atlassian.net/browse/ED-1684

refactor(action): handle tablestore action data before submit

---

src/hooks/Rule/useDataHandler.ts

https://emqx.atlassian.net/browse/ED-1717

fix(action): remove key if value is empty

---

package.json
src/components/SchemaFormItem.tsx
yarn.lock

Fixed IoTDB batch template issue: https://emqx.atlassian.net/browse/ED-1713

chore(utils): update shared-ui-utils to 0.0.16

---

src/hooks/Rule/KeysInRule.ts
src/hooks/Rule/RuleFunc.json
src/i18n/RuleSyntax.js

https://emqx.atlassian.net/browse/ED-1718

fix(rule): adapt str_utf16_le and sqlserver_bin2hexstr funcs in rule

---

src/i18n/Dashboard.js
src/views/Base/LicenseTipDialog.vue

https://emqx.atlassian.net/browse/ED-1714

refactor(license): update evaluation license warning message

---

src/hooks/Flow/useFlowNode.ts
src/hooks/Rule/bridge/useBridgeTypeValue.ts
yarn.lock

https://emqx.atlassian.net/browse/ED-1719

fix(flow): add tablestore node

---

src/components/InputWithPlaceholderSelect.vue
src/components/SchemaForm.tsx
src/components/SchemaFormItem.tsx
src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Schema/useSchemaForm.ts
src/types/enum.ts

https://emqx.atlassian.net/browse/ED-1717

fix(schema): optimize input with placeholder select

---

src/hooks/Rule/useDataHandler.ts
src/types/schemas/actions.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/connectors.schemas.ts
src/types/schemas/opentelemetry.schemas.ts

https://emqx.atlassian.net/browse/ED-1717
https://emqx.atlassian.net/browse/ED-1716

fix(connector & action): issue when saving as copy; simple oneof

---

package.json
yarn.lock

https://emqx.atlassian.net/browse/ED-1721

chore(deps): bump version

---

src/hooks/Schema/useSchemaForm.ts

https://emqx.atlassian.net/browse/ED-1726

fix(schema): do not show boolean options if there are other type

---

src/schemaText/schema-text-en.json
src/schemaText/schema-text-zh.json

https://emqx.atlassian.net/browse/ED-1725

fix(monitoring): update large heap desc

---

src/schemaText/actionText/action-label-en.json
src/schemaText/actionText/action-label-zh.json
src/types/schemas/bridges.schemas.ts
src/types/schemas/configs.schemas.ts
src/types/schemas/connectors.schemas.ts
src/types/schemas/gateways.schemas.ts
src/types/schemas/sources.schemas.ts

https://emqx.atlassian.net/browse/ED-1724

feat(sources): support no local to mqtt source config

---

src/components/ObjectArrayEditor.vue
src/hooks/Rule/connector/useComponentsHandlers.ts

https://emqx.atlassian.net/browse/ED-1723

fix(connector): support static client ids for mqtt connector

---

src/views/Dashboard/components/NodesGraphCard.vue
yarn.lock

https://emqx.atlassian.net/browse/ED-1722

fix(nodes): fix cluster name too long issue

---

src/components/ObjectArrayEditor.vue
src/hooks/Rule/bridge/useComponentsHandlers.ts
src/hooks/Rule/connector/useComponentsHandlers.ts
src/hooks/useI18nPrefix.ts
src/types/schemas/actions.schemas.ts
src/types/schemas/bridges.schemas.ts
src/types/schemas/connectors.schemas.ts
src/types/schemas/dashboard.schemas.ts
src/types/schemas/dashboardSingleSignOn.schemas.ts

https://emqx.atlassian.net/browse/ED-1723

feat(connector): support static ids for mqtt connector

---

src/hooks/Rule/transform/useMessageTransform.ts
src/views/General/AuditLog.vue

https://emqx.atlassian.net/browse/ED-1736
thanks @0721Betty

fix(msg transform): wrong validation

---

src/views/Config/ClusterLinking/components/ClusterLinkingForm.vue
src/views/General/components/SSOForm/LDAPForm.vue
src/views/General/components/SSOForm/OIDCForm.vue
src/views/RuleEngine/Schema/components/ExternalSchemaForm.vue

https://emqx.atlassian.net/browse/ED-1728

fix(cluster linking): use CustomInputPassword

---

src/components/ObjectArrayEditor.vue
src/components/SchemaForm.tsx

https://emqx.atlassian.net/browse/ED-1731

fix(schema): validate form after adding item

---

src/hooks/Rule/useDataHandler.ts
src/hooks/usePaging.ts
src/views/RuleEngine/Bridge/BridgeDetail.vue
src/views/RuleEngine/Source/SourceDetail.vue
src/views/RuleEngine/components/ActionAndSourceFilterForm.vue
src/views/RuleEngine/components/ActionAndSourceList.vue

https://emqx.atlassian.net/browse/ED-1737

refactor(action): finish some detail

---

.github/workflows/build_emqx_for_test.yaml
.github/workflows/build_enterprise_package.yaml
.github/workflows/build_oss_package.yaml
.github/workflows/check_newest_schema.yaml
src/i18n/components.js
src/views/General/components/APIKeyDialog.vue

https://emqx.atlassian.net/browse/ED-1748

refactor(i18n): update component translations to plural forms

---

scripts/transformer/filterTagsSchema.js
src/hooks/Auth/useAuthHelp.ts
src/i18n/AuthDoc.js
src/i18n/RuleEngine.js
src/i18n/RuleEvent.js
src/types/schemas/metrics.schemas.ts
src/types/schemas/rules.schemas.ts
src/views/General/APIKey.vue

https://emqx.atlassian.net/browse/ED-1756
https://emqx.atlassian.net/browse/ED-1752
https://emqx.atlassian.net/browse/ED-1745

refactor(api key): add api_key column

---

src/components/ListenerDrawer/ListenerDrawer.vue
src/hooks/Config/useListenerDrawer.ts
src/hooks/Rule/useDataHandler.ts
src/i18n/Clients.js
src/i18n/RuleSyntax.js
src/views/RuleEngine/components/TestSQLContextForm.vue

https://emqx.atlassian.net/browse/ED-1763
https://emqx.atlassian.net/browse/ED-1759

fix(listener): add exit confirmation

---

src/components/SchemaForm.tsx
src/hooks/Flow/useGenerateFlowDataUtils.ts

https://emqx.atlassian.net/browse/ED-1758

fix(flow): MQTT action and source have the same name

---

src/components/ListenerDrawer/CustomConfigs.vue
src/i18n/Auth.js
src/style/normalize.scss
src/views/Auth/components/AuthnManager.vue
src/views/Auth/components/AuthnUsersImport.vue
src/views/Auth/components/AuthzManager.vue
src/views/Clients/Clients.vue
src/views/Clients/components/ClientFieldSelect.vue
src/views/Clients/components/MessageListDialog.vue
src/views/Config/BasicConfig/DurableSessions.vue
src/views/Config/BasicConfig/ForceShutdown.vue
src/views/Config/BasicConfig/SystemTopics.vue
src/views/RuleEngine/components/ActionAndSourceList.vue
src/views/Settings/Settings.vue

https://emqx.atlassian.net/browse/ED-1760

refactor(auth): add text for button

---

src/views/Clients/components/MessageListDialog.vue
src/views/General/HotUpgrade.vue
src/views/General/components/SSOForm/LDAPForm.vue
src/views/General/components/SSOForm/OIDCForm.vue
src/views/General/components/SSOForm/SAMLForm.vue

https://emqx.atlassian.net/browse/ED-1760

style(sso): unify some style

---

src/hooks/Webhook/useWebhookUtils.ts
src/hooks/usePaging.ts
src/views/RuleEngine/components/ActionAndSourceFilterForm.vue
yarn.lock

https://emqx.atlassian.net/browse/ED-1767
https://emqx.atlassian.net/browse/ED-1768

fix(action): logic to detect if it is a webhook action

---

src/views/RuleEngine/components/ActionAndSourceList.vue

https://emqx.atlassian.net/browse/ED-1770

fix(action): issue of overflow tooltip

---

src/i18n/BasicConfig.js
src/views/Config/BasicConfig/Mqtt.vue

https://emqx.atlassian.net/browse/ED-1771

fix(log): plural form of title

---

src/i18n/BasicConfig.js
src/types/schemas/rules.schemas.ts
src/views/Alarm/CurrentAlarm.vue

https://emqx.atlassian.net/browse/ED-1771

fix(log): plural form of Audit Log

---

src/views/Alarm/CurrentAlarm.vue

https://emqx.atlassian.net/browse/ED-1775

fix(alarm): permission control for button

---

src/views/RuleEngine/components/ActionAndSourceList.vue

https://emqx.atlassian.net/browse/ED-1776

fix(source): can not delete source

---

src/components/global-components.ts
src/global-components.d.ts
src/i18n/Extension.ts
src/types/extension.d.ts
src/views/Config/BasicConfig/Retainer.vue
src/views/Retained/Retained.vue
src/views/RuleEngine/components/ActionAndSourceFilterForm.vue

https://emqx.atlassian.net/browse/ED-1747
https://emqx.atlassian.net/browse/ED-1685

refactor(retainer): remove retainer.enable

---

src/i18n/Dashboard.ts
src/plugins/permissionsPlugin.ts
src/shims-vue.d.ts
src/types/dashboard.d.ts
src/views/General/License.vue

https://emqx.atlassian.net/browse/ED-1754

refactor(license): replace connections with sessions

---

src/i18n/RuleEngine.js
src/i18n/RuleEvent.js
src/types/schemas/rules.schemas.ts

https://emqx.atlassian.net/browse/ED-1778

fix(rule): adapt event changed

---

src/components/KeyAndValueEditor.vue
src/components/SchemaForm.tsx
src/views/Config/BasicConfig/Mqtt.vue

https://emqx.atlassian.net/browse/ED-1772

fix(mqtt): rules for `client_attrs_init`

---

src/hooks/useOperationConfirm.ts

https://emqx.atlassian.net/browse/ED-1780

fix(msg trans): message after deleting

---

src/hooks/Rule/rule/useDebugRule.ts

https://emqx.atlassian.net/browse/ED-1778

fix(rule): reg to match event type

---

src/hooks/Rule/useActionAndSourceStatus.ts
src/views/RuleEngine/components/TargetItemStatus.vue

https://emqx.atlassian.net/browse/ED-1781

fix(action): correct status label

---

src/components/Metrics/TypeMetricsItem.vue

https://emqx.atlassian.net/browse/ED-1797

fix(action): style issue

---

src/hooks/Rule/bridge/useSchemaBridgePropsLayout.ts
src/hooks/Rule/connector/useSchemaConnectorPropsLayout.ts
src/types/schemas/actions.schemas.ts
src/types/schemas/bridges.schemas.ts
src/types/schemas/connectors.schemas.ts
src/types/schemas/monitor.schemas.ts
src/types/schemas/rules.schemas.ts

https://emqx.atlassian.net/browse/ED-1796

refactor(action): adapt max_inflight in pulsar

---

src/views/Webhook/Webhook.vue
src/views/Webhook/WebhookDetail.vue

https://emqx.atlassian.net/browse/ED-1785

fix(webhook): unexpected error message

---

src/views/General/resource_dict.json
yarn.lock

https://emqx.atlassian.net/browse/ED-1784
https://emqx.atlassian.net/browse/ED-1796

fix(audit log): correct some text in dict

---

src/api/plugins.ts
src/common/http.js
src/components/TipContainer.vue
src/i18n/Plugins.js
src/views/Plugins/PluginInstall.vue

https://emqx.atlassian.net/browse/ED-1795

refactor(plugin): guide to exec command before installing
